### ISSUE TITLE
font of variables too small

### ISSUE THREAD

**Issue by aleruete** [dreamRs/esquisse#104]
Hi, 
I don´t know exactly since which version but the font of the variables in the esquisser became too small. I am using the esquisse version 0.3.0. Is there something I am missing?

Cheers,

Alejandro

**Comment by aleruete** [comment]
![Untitled](https://user-images.githubusercontent.com/10223186/75237896-75358300-57c0-11ea-944d-d0b6b10d93bb.png)

**Comment by pvictor** [comment]
Hello,
You can override font size with CSS, like this : 

```r
tags$style(".container-drag-source, .box-dad {font-size: 20px;}")
```

You can put this code somewhere in your UI.

Victor

**Comment by aleruete** [comment]
Awesome, great! Thank you
