### ISSUE TITLE
Converting between variable types

### ISSUE THREAD

**Issue by EpiPhys** [dreamRs/esquisse#11]
It would be great to be able to convert a numeric variable to a factor one for example

**Comment by pvictor** [comment]
Little update:
I wrote a module to convert a variable to a specific class, I'll integrate it into the main addin soon.
It's called `?coerceUI`, if you want to check it out.

**Comment by EpiPhys** [comment]
Thanks! I'm looking forward to trying.

Maïa

Le mar. 12 juin 2018 à 16:14, Victor Perrier <notifications@github.com> a
écrit :

**Comment by pvictor** [comment]
Hi,
The module has been integrated, it's still experimental at the moment, so you have to set an options to activate it : 

```r
options("esquisse.coerceVars" = TRUE)
esquisse:::esquisser()
```

Victor

**Comment by EpiPhys** [comment]
Great!

Maïa

Le jeu. 21 juin 2018 à 11:04, Victor Perrier <notifications@github.com> a
écrit :
