### ISSUE TITLE
dataset not loading in `esquisserServer` unless loaded via `chooseDataServer`

### ISSUE THREAD

**Issue by ChristopherBarrington** [dreamRs/esquisse#117]
In the CRAN version the following mwe works as expected:

```r
ui <- navbarPage(
  title = "My navbar app",
  tabPanel(
    title = "esquisse",
    esquisserUI(
      id = "esquisse",
      header = FALSE,
      container = esquisseContainer(
        fixed = c(50, 0, 0, 0)
      )
    )
  )
)

server <- function(input, output, session) {
  
  callModule(module = esquisserServer, id = "esquisse", data=reactiveValues(data=data.frame(x=rnorm(100), y=rnorm(100), group=sample(x=letters[1:3], size=100, replace=TRUE)), name='data'))
  
}

runApp(shinyApp(ui, server))
```

Using the master branch of the repository, however, the plot is not rendered; no variables are displayed from which to choose aesthetics. I have to use the `choose_data` process to get a dataset to load.

I think it is [this line](https://github.com/dreamRs/esquisse/blob/626cbe584f43a6a13a6d5cce3192fcf912e08cb0/R/esquisserServer.R#L69) where the `ignoreInit=TRUE` means that the initialisation from the server argument is ignored and the reactive only updated after initialised once the load a dataset module is used. In my fork I change set `ignoreInit=FALSE` and the code works as expected.

Thanks for the work!

**Comment by pvictor** [comment]
Thanks for reporting that, the `ignoreInit` seems indeed unnecessary, I removed it.
It doesn't affect comportment fixed in https://github.com/dreamRs/esquisse/pull/110

Victor
