### ISSUE TITLE
Coerce option not available while importing data

### ISSUE THREAD

**Issue by sarthi2395** [dreamRs/esquisse#118]
I created a shiny app and invoked the esquisse module in the app with import data selected as TRUE. However, I notice that when I run the app locally from rstudio, I get an additional option to coerce the data whereas when I run it from a shiny server, the coerce dropdown does not appear. I am guessing this is due to a missing package but I cannot find anything on this in the docs.

My code
````r
library(shiny)
library(esquisse)
options(shiny.maxRequestSize = 30*1024^2)

ui <- fluidPage(
  esquisserUI(
    id = "esquisse", 
    header = FALSE,
    choose_data = TRUE,
    container = esquisseContainer(fixed = TRUE)
  )
)

server <- function(input, output, session) {
  
  data_r <- reactiveValues(data = data.frame(), name = "default")
  
  callModule(module = esquisserServer, id = "esquisse", data = NULL, dataModule = "ImportFile", sizeDataModule="l")
  
}

shinyApp(ui, server)
````

**Comment by xiangnandang** [comment]
```
options("esquisse.coerceVars" = TRUE)
```

try put this in your app.R file

**Comment by sarthi2395** [comment]
Tried. Does not work!

**Comment by xiangnandang** [comment]
It worked for me:
![image](https://user-images.githubusercontent.com/36307794/85508584-5bffe000-b5c2-11ea-9db1-449ef362c858.png)

only change is the single line I suggested
```
library(shiny)
library(esquisse)
options(shiny.maxRequestSize = 30*1024^2)
options("esquisse.coerceVars" = TRUE)

ui <- fluidPage(
  esquisserUI(
    id = "esquisse", 
    header = FALSE,
    choose_data = TRUE,
    container = esquisseContainer(fixed = TRUE)
  )
)

server <- function(input, output, session) {
  
  data_r <- reactiveValues(data = data.frame(), name = "default")
  
  callModule(module = esquisserServer, id = "esquisse", data = NULL, dataModule = "ImportFile", sizeDataModule="l")
  
}

shinyApp(ui, server)
```

**Comment by xiangnandang** [comment]
could you make sure you have the most updated version installed (ideally from install_github)?

**Comment by sarthi2395** [comment]
I do have. Removing and adding the package back and adding ````options("esquisse.coerceVars" = TRUE)```` seems to have fixed it. Thanks!
