### ISSUE TITLE
chooseDataUI tooltip and default

### ISSUE THREAD

**Issue by DanChaltiel** [dreamRs/esquisse#119]
Hi dreamRs devs,

I'm very fond of your UI and I'm using your `chooseData` module in my RStudio addin [crosstableAssistant](https://github.com/DanChaltiel/crosstableAssistant).

However, as a module, there are a few features that might be improved with a bit of customizability:

- the tooltip, which only displays "select the variables you want to use to create graphs". As my app doesn't make graphs, this seems a bit ridiculous.
- the dropdown list, which cannot have a default chooser dataset, nor a customizable default list. This can be cumbersome sometimes.

Would you consider adding support for those?

Actually, though it may require a bit of refactoring, I think this module would even deserve a repo of its own, as I couldn't find any standalone shiny data-choosing module, especially one as good as yours. I might be able to do the refactoring myself in a fork if you want some help.

**Comment by pvictor** [comment]
Hello Dan,

Cool package you've made! Indeed there's something to improve in this module, and yes I've plan to put it in a new package with more capabilities, hope I can do this in the summer.

For your current issue:

* it'll be great to have the ability to customize all labels (including the tooltip), in particular with a view to internationalisation 
* you mean using something elese than ggplot2 dataset as default ? that's doable

Victor

**Comment by DanChaltiel** [comment]
Hi Victor,

Thank you very much :-) If you happen to use it (or to use the base R package `crosstable`), I'm looking for reviews and ideas of improvement, so don't hesitate to fill an issue or a feature request.

For my current issue:

- indeed, although only the tooltip seems really oriented to me. Customizing other labels could be a plus but I'm not sure it is as important as the tooltip
- yes, I would like to be able to use another default list than the ggplot2 datasets (e.g. the few from `crosstable`), and I'd also like to be able to set a default, selected dataset, so that I don't need to browse the list if I can guess my user's choice.
- bonus thought: when you select variables to keep, the displayed class is only the first one. This can be a problem when you use labeled datasets (from `Hmisc`, `expss`, `haven`...), as the first class is always "labeled". You might want to paste/collapse them here or remove the "labeled" value arbitrarily (I do the second option sometimes).

Dan

**Comment by pvictor** [comment]
All those functionnalities are now in package {datamods}: https://github.com/dreamRs/datamods
