### ISSUE TITLE
Issue in running esquisse addin

### ISSUE THREAD

**Issue by sarthi2395** [dreamRs/esquisse#121]
I recently did a clean install of all my R packages along with which I also installed esquisse package from github repo. Right now, when I initiate the add-in, I get this error.

````
esquisse::esquisser()
Error in col2Hex(viridis_pal(option = "viridis")(10)) : 
  could not find function "col2Hex"
````

This used to work flawlessly before I updated my libraries. Could anyone help me out with this?

EDIT:

I noticed in the default-options.R file, the function ````default_cols```` has col2Hex referred. But when I searched R vignettes for ````gplots```` package, the **H** seems to be in lowercase, as **col2hex**.  I guess that is causing this issue?

**Comment by pvictor** [comment]
This should be fixed if you re-install from GitHub.
`col2Hex` was an internal function, now removed.
