### ISSUE TITLE
[Feature Request] dragulaInput arrange outputs in grid

### ISSUE THREAD

**Issue by JamesBrownSEAMS** [dreamRs/esquisse#123]
It would be useful to be able to specify how many rows the outputs of the `dragulaInput` module were spread over to avoid overcrowding the UI element. In a recent example I had 8 outputs but I was not able to assign useful names without them being obscured by the decreased width of each box. It would be ideal to be able to split them over multiple rows to avoid this issue. For example, convert this:
![image](https://user-images.githubusercontent.com/53085970/87427481-c233bd80-c5d8-11ea-8c45-c2e5848d9fa2.png)
to this:
![image](https://user-images.githubusercontent.com/53085970/87427501-cc55bc00-c5d8-11ea-87db-2a3062a30f61.png)
From a visual perspective in the case of uneven contents of each row, consistent box dimentions would be prefereable, for example:
![image](https://user-images.githubusercontent.com/53085970/87427555-decff580-c5d8-11ea-9840-8203e2b9d6de.png)
Rather than:
![image](https://user-images.githubusercontent.com/53085970/87427616-f8713d00-c5d8-11ea-8276-4acb9a6929fc.png)

**Comment by pvictor** [comment]
Hello,

Very interesting, this should be doable with a CSS grid (https://cssgrid-generator.netlify.app/), I'll look into it.

Victor

**Comment by pvictor** [comment]
Hello,

If you install dev version, you can try:

```r
library(shiny)
library(esquisse)

ui <- fluidPage(
  tags$h2("Demo dragulaInput"),
  tags$br(),
  fluidRow(
    column(
      width = 6,
      
      dragulaInput(
        inputId = "dad1",
        label = "Default:",
        sourceLabel = "Source",
        targetsLabels = c("Target 1", "Target 2"),
        choices = month.abb,
        width = "100%"
      ),
      verbatimTextOutput(outputId = "result1"),
      
      tags$br(),
      
      dragulaInput(
        inputId = "dad3",
        label = "On same row:",
        sourceLabel = "Source",
        targetsLabels = c("Target 1", "Target 2"),
        choices = month.abb,
        width = "100%",
        ncolSource = 1,
        ncolGrid = 3
      ),
      verbatimTextOutput(outputId = "result3")
    ),
    
    column(
      width = 6,
      dragulaInput(
        inputId = "dad2",
        label = "Two rows:",
        sourceLabel = "Source",
        targetsLabels = c("x", "y", "color", "fill", "size", "facet"),
        choices = names(mtcars),
        width = "100%",
        ncolGrid = 3
      ),
      verbatimTextOutput(outputId = "result2"),
      
      tags$br(),
      
      dragulaInput(
        inputId = "dad4",
        label = "Two rows not filled:",
        sourceLabel = "Source",
        targetsLabels = c("x", "y", "color", "fill", "size"),
        choices = names(mtcars),
        width = "100%",
        ncolGrid = 3
      ),
      verbatimTextOutput(outputId = "result4")
    )
  )
)


server <- function(input, output, session) {
  
  output$result1 <- renderPrint(str(input$dad1))
  
  output$result2 <- renderPrint(str(input$dad2))
  
  output$result3 <- renderPrint(str(input$dad3))
  
  output$result4 <- renderPrint(str(input$dad4))
  
}

if (interactive())
  shinyApp(ui = ui, server = server)
```

Which gives:

![image](https://user-images.githubusercontent.com/4415580/93335471-cb364a80-f826-11ea-915d-546a953d6bd0.png)

Victor

**Comment by JamesBrownSEAMS** [comment]
This is great, I'll download the dev version and see how it integrates into my application.

Thanks for the update
