### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by ChiristmasWu** [dreamRs/esquisse#13]
> devtools::install_github("dreamRs/esquisse")
Downloading GitHub repo dreamRs/esquisse@master
from URL https://api.github.com/repos/dreamRs/esquisse/zipball/master
Installing esquisse
Downloading GitHub repo dreamRs/shinyWidgets@master
from URL https://api.github.com/repos/dreamRs/shinyWidgets/zipball/master
Installing shinyWidgets
"D:/PROGRA~2/R/R-33~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/wushengdan/AppData/Local/Temp/RtmpW0eLbk/devtools1d00eb8790a/dreamRs-shinyWidgets-07b07d8"  \
  --library="D:/Program Files/R/R-3.3.1/library" --install-tests 

ERROR: dependency 'shiny' is not available for package 'shinyWidgets'
* removing 'D:/Program Files/R/R-3.3.1/library/shinyWidgets'
Error: Command failed (1)

**Comment by pvictor** [comment]
Can you re-try in fresh new R session ? 

```r
devtools::install_github("dreamRs/esquisse")
```

Victor

**Comment by pvictor** [comment]
Hello,
{esquisse} is now on CRAN and binaries have been build, you can install with : 

```r
install.packages("esquisse")

# with all dependencies
install.packages("esquisse", dependencies = c("Imports", "Suggests"))
```

If you have new installation problems with this command, please open a new issue.

Victor
