### ISSUE TITLE
Add the possibility to define a weight aesthetic

### ISSUE THREAD

**Issue by larmarange** [dreamRs/esquisse#132]
for example, take the following dataset:

```r
df <- as_tibble(Titanic)
```

How to assign `n` to the `weight` aesthetic?

Regards

**Comment by pvictor** [comment]
Currently, if you set aesthetics to `x` and `y` and select `bar` as geom, it will map `y` to `weight`, giving: 

```r
library(ggplot2)
df <- tibble::as_tibble(Titanic)
ggplot(df) +
  aes(x = Class, weight = n) +
  geom_bar(fill = "#0c4c8a") +
  theme_minimal()
```

What's your use-case ?

Victor

**Comment by larmarange** [comment]
Thank you. I didn't know that trick.

I'm working mainly with survey data and most of them have sampling weights that should be taken into account. In such case, weight aesthetic should be used for any graph.

```r
library(survey)
data(api)

library(ggplot2)
ggplot(apistrat) +
  aes(x = api99, weight = pw) +
  geom_histogram(bins = 30L, fill = "#0c4c8a") +
  theme_minimal()

ggplot(apistrat) +
  aes(x = stype, y = api99, weight = pw) +
  geom_boxplot() +
  theme_minimal()
```

**Comment by pvictor** [comment]
Thanks for the examples, I see your point.

I can add an new box for selecting `weight` aesthetic, my only concern is available horizontal space to put all boxes, I'll try to see what it gives.
I may have to put some aesthetics as optionnal in a new argument of the addin/functions.

**Comment by larmarange** [comment]
Thanks for your feedback.

Just a quick suggestion: maybe instead of an argument in the addin function you could consider a checkbox or a button in the interface to show/hide advanced aesthetics.

Regards

**Comment by pvictor** [comment]
It is now available in the GitHub version and will be released on CRAN soon, please re-open this issue if you encounter any trouble.

**Comment by larmarange** [comment]
Thanks
