### ISSUE TITLE
Change content

### ISSUE THREAD

**Issue by trf66** [dreamRs/esquisse#133]
Hi, 
Thank your for this great job !  I am in admiration for your work.

For few days i had tried to display the app in a shiny DB and I haven't successfull to change the language (put all text in french). 
When i tried to run the app with files in "R/" after custom labels, i think i did wrong because anithing change (display in english). 
Somebody have an idea/ a suggestion / code  to help me please ?

best

**Comment by pvictor** [comment]
Salut,

As-tu essayé de réinstaller le package après avoir modifié les labels ? Via le bouton "Install & Restart" de RStudio ou via un `devtools::load_all()` ?

Victor

**Comment by trf66** [comment]
Salut Victor! 
Super conseil, ca a bien fonctionné :)
Lorsque je teste dans un DB non sécurisé, tout roule. 
Par contre lorsque le dossier R contient d'autres données (module de sécurisation de l'appli), ca beug.
Aurais-tu un autre conseil à me donner pour gérer ça ? 

<img width="1237" alt="screen" src="https://user-images.githubusercontent.com/48265905/100641318-991d8a80-3337-11eb-8241-3cd95fa343ff.png">

**Comment by pvictor** [comment]
Cela pourrait être sympa d'avoir une possibilité de changer la langues ou les labels directement dans le package, mais c'est un gros chantier je pense.
