### ISSUE TITLE
Error in check_theme_exist(ggthemes, package = "ggthemes") :    could not find function "check_theme_exist"

### ISSUE THREAD

**Issue by sajjadasaf** [dreamRs/esquisse#137]
I install ggthems and working properly but when try to use esquisse then it show the following error

 esquisse:::esquisser()
Error in check_theme_exist(ggthemes, package = "ggthemes") : 
  could not find function "check_theme_exist"
I am using linux mint rstudio server

Please help me to solve this problem

**Comment by pvictor** [comment]
Which version have you installed ? You should try to re-install from CRAN.
If this still occurs, please share result of `sessioninfo::session_info()`

Victor

**Comment by sajjadasaf** [comment]
Thank you for your reply,
I am using R 4.0.3 and install esquisse from CRAN v 0.3.1

Below are the required informations




─ Session info ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.3 (2020-10-10)
 os       Linux Mint 20.1             
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Asia/Muscat                 
 date     2021-02-09                  

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 !  package      * version date       lib source        
    ade4           1.7-16  2020-10-28 [1] CRAN (R 4.0.3)
    ape          * 5.4-1   2020-08-13 [1] CRAN (R 4.0.3)
    assertthat     0.2.1   2019-03-21 [3] CRAN (R 4.0.0)
    beeswarm       0.2.3   2016-04-25 [1] CRAN (R 4.0.3)
    Biobase        2.50.0  2020-10-27 [1] Bioconductor  
    BiocGenerics   0.36.0  2020-10-27 [1] Bioconductor  
    BiocManager    1.30.10 2019-11-16 [1] CRAN (R 4.0.3)
    biomformat     1.18.0  2020-10-27 [1] Bioconductor  
    Biostrings     2.58.0  2020-10-27 [1] Bioconductor  
    bslib          0.2.4   2021-01-25 [3] CRAN (R 4.0.3)
 VP cachem         1.0.1   2021-02-03 [3] CRAN (R 4.0.3)
    callr          3.5.1   2020-10-13 [3] CRAN (R 4.0.3)
    cli            2.3.0   2021-01-31 [3] CRAN (R 4.0.3)
    cluster        2.1.0   2019-06-19 [4] CRAN (R 4.0.0)
    codetools      0.2-18  2020-11-04 [4] CRAN (R 4.0.3)
    colorspace     2.0-0   2020-11-11 [3] CRAN (R 4.0.3)
    corrplot     * 0.84    2017-10-16 [1] CRAN (R 4.0.3)
    crayon         1.4.0   2021-01-30 [3] CRAN (R 4.0.3)
    data.table     1.13.6  2020-12-30 [1] CRAN (R 4.0.3)
    desc           1.2.0   2018-05-01 [3] CRAN (R 4.0.0)
    devtools     * 2.3.2   2020-09-18 [3] CRAN (R 4.0.2)
    digest         0.6.27  2020-10-24 [3] CRAN (R 4.0.3)
    dplyr          1.0.4   2021-02-02 [1] CRAN (R 4.0.3)
    ellipsis       0.3.1   2020-05-15 [3] CRAN (R 4.0.0)
    esquisse     * 0.3.1   2020-09-27 [1] CRAN (R 4.0.3)
    fastmap        1.1.0   2021-01-25 [3] CRAN (R 4.0.3)
    foreach        1.5.1   2020-10-15 [1] CRAN (R 4.0.3)
    fs             1.5.0   2020-07-31 [3] CRAN (R 4.0.2)
    generics       0.1.0   2020-10-31 [1] CRAN (R 4.0.3)
    ggbeeswarm   * 0.6.0   2017-08-07 [1] CRAN (R 4.0.3)
    ggplot2      * 3.3.3   2020-12-30 [3] CRAN (R 4.0.3)
    ggthemes       4.2.4   2021-01-20 [1] CRAN (R 4.0.3)
    glue           1.4.2   2020-08-27 [3] CRAN (R 4.0.2)
    gtable         0.3.0   2019-03-25 [3] CRAN (R 4.0.0)
    hms            1.0.0   2021-01-13 [1] CRAN (R 4.0.3)
    htmltools      0.5.1.1 2021-01-22 [3] CRAN (R 4.0.3)
    httpuv         1.5.5   2021-01-13 [3] CRAN (R 4.0.3)
    igraph         1.2.6   2020-10-06 [3] CRAN (R 4.0.2)
    IRanges        2.24.1  2020-12-12 [1] Bioconductor  
    iterators      1.0.13  2020-10-15 [1] CRAN (R 4.0.3)
    jquerylib      0.1.3   2020-12-17 [3] CRAN (R 4.0.3)
    jsonlite       1.7.2   2020-12-09 [3] CRAN (R 4.0.3)
    later          1.1.0.1 2020-06-05 [3] CRAN (R 4.0.0)
    lattice        0.20-41 2020-04-02 [4] CRAN (R 4.0.0)
    lifecycle      0.2.0   2020-03-06 [3] CRAN (R 4.0.0)
    magrittr       2.0.1   2020-11-17 [3] CRAN (R 4.0.3)
    MASS           7.3-53  2020-09-09 [4] CRAN (R 4.0.2)
    Matrix         1.3-2   2021-01-06 [4] CRAN (R 4.0.3)
    memoise        2.0.0   2021-01-26 [3] CRAN (R 4.0.3)
    mgcv           1.8-33  2020-08-27 [4] CRAN (R 4.0.2)
    microbiome   * 1.12.0  2020-10-27 [1] Bioconductor  
    mime           0.9     2020-02-04 [3] CRAN (R 4.0.0)
    miniUI         0.1.1.1 2018-05-18 [3] CRAN (R 4.0.0)
    multtest       2.46.0  2020-10-27 [1] Bioconductor  
    munsell        0.5.0   2018-06-12 [3] CRAN (R 4.0.0)
    nlme           3.1-152 2021-02-04 [1] CRAN (R 4.0.3)
    permute        0.9-5   2019-03-12 [1] CRAN (R 4.0.3)
    phyloseq     * 1.34.0  2020-10-27 [1] Bioconductor  
    pillar         1.4.7   2020-11-20 [3] CRAN (R 4.0.3)
    pkgbuild       1.2.0   2020-12-15 [3] CRAN (R 4.0.3)
    pkgconfig      2.0.3   2019-09-22 [3] CRAN (R 4.0.0)
    pkgload        1.1.0   2020-05-29 [3] CRAN (R 4.0.0)
    plyr           1.8.6   2020-03-03 [1] CRAN (R 4.0.3)
    prettyunits    1.1.1   2020-01-24 [3] CRAN (R 4.0.0)
    processx       3.4.5   2020-11-30 [3] CRAN (R 4.0.3)
    progress       1.2.2   2019-05-16 [1] CRAN (R 4.0.3)
    promises       1.1.1   2020-06-09 [3] CRAN (R 4.0.1)
    ps             1.5.0   2020-12-05 [3] CRAN (R 4.0.3)
    purrr          0.3.4   2020-04-17 [3] CRAN (R 4.0.0)
    R6             2.5.0   2020-10-28 [3] CRAN (R 4.0.3)
    RColorBrewer * 1.1-2   2014-12-07 [3] CRAN (R 4.0.0)
    Rcpp           1.0.6   2021-01-15 [3] CRAN (R 4.0.3)
    remotes        2.2.0   2020-07-21 [3] CRAN (R 4.0.2)
    reshape2       1.4.4   2020-04-09 [1] CRAN (R 4.0.3)
    rhdf5          2.34.0  2020-10-27 [1] Bioconductor  
    rhdf5filters   1.2.0   2020-10-27 [1] Bioconductor  
    Rhdf5lib       1.12.1  2021-01-26 [1] Bioconductor  
    rlang          0.4.10  2020-12-30 [3] CRAN (R 4.0.3)
    rprojroot      2.0.2   2020-11-15 [3] CRAN (R 4.0.3)
    rstudioapi     0.13    2020-11-12 [3] CRAN (R 4.0.3)
    Rtsne          0.15    2018-11-10 [1] CRAN (R 4.0.3)
    S4Vectors      0.28.1  2020-12-09 [1] Bioconductor  
    sass           0.3.1   2021-01-24 [3] CRAN (R 4.0.3)
    scales         1.1.1   2020-05-11 [3] CRAN (R 4.0.0)
    sessioninfo    1.1.1   2018-11-05 [3] CRAN (R 4.0.0)
    shiny          1.6.0   2021-01-25 [3] CRAN (R 4.0.3)
    shinyWidgets   0.5.7   2021-02-03 [1] CRAN (R 4.0.3)
    stringi        1.5.3   2020-09-09 [3] CRAN (R 4.0.2)
    stringr        1.4.0   2019-02-10 [3] CRAN (R 4.0.0)
    survival       3.2-7   2020-09-28 [4] CRAN (R 4.0.2)
    testthat       3.0.1   2020-12-17 [3] CRAN (R 4.0.3)
    tibble         3.0.6   2021-01-29 [3] CRAN (R 4.0.3)
    tidyr          1.1.2   2020-08-27 [1] CRAN (R 4.0.3)
    tidyselect     1.1.0   2020-05-11 [1] CRAN (R 4.0.3)
    tinytex        0.29    2021-01-21 [3] CRAN (R 4.0.3)
    usethis      * 2.0.0   2020-12-10 [3] CRAN (R 4.0.3)
    vctrs          0.3.6   2020-12-17 [3] CRAN (R 4.0.3)
    vegan          2.5-7   2020-11-28 [1] CRAN (R 4.0.3)
    vipor          0.4.5   2017-03-22 [1] CRAN (R 4.0.3)
    withr          2.4.1   2021-01-26 [3] CRAN (R 4.0.3)
    xfun           0.20    2021-01-06 [3] CRAN (R 4.0.3)
    xtable         1.8-4   2019-04-21 [3] CRAN (R 4.0.0)
    XVector        0.30.0  2020-10-27 [1] Bioconductor  
    zlibbioc       1.36.0  2020-10-27 [1] Bioconductor  

[1] /home/sajjad/R/x86_64-pc-linux-gnu-library/3.4
[2] /usr/local/lib/R/site-library
[3] /usr/lib/R/site-library
[4] /usr/lib/R/library

 V ── Loaded and on-disk version mismatch.
 P ── Loaded and on-disk path mismatch.

**Comment by pvictor** [comment]
Thanks, that's weird, I don't see anything wrong...
If you type `esquisse:::check_theme_exist` in console, you get an error ?

**Comment by sajjadasaf** [comment]
Hello Pvictor,
Thank you for your reply.
Yes really weird I don't know what is wrong here.
I almost reinstall everything but still same error. 
By typing the above below are the results.
Thank you for your help


> esquisse:::check_theme_exist
function (x, package = "hrbrthemes") 
{
    vapply(X = paste0("theme_", x), FUN = function(fun) {
        exists(fun, where = asNamespace(package), mode = "function")
    }, FUN.VALUE = logical(1), USE.NAMES = FALSE)
}
<bytecode: 0x55f2d7ea9770>
<environment: namespace:esquisse>

**Comment by pvictor** [comment]
Have an option `"esquisse.themes"` set ? e.g. what gives : `getOption("esquisse.themes")` ?

**Comment by opendatasurgeon** [comment]
Hello, I downloaded the dev version of the package, and I am also getting this error. My `getOption` gives me this:

`````r
getOption("esquisse.themes")
function () 
{
    ggplot2 <- c("bw", "classic", "dark", "gray", 
        "light", "linedraw", "minimal", "void")
    ggplot2 <- setNames(as.list(paste0("theme_", ggplot2)), 
        ggplot2)
    themes <- list(ggplot2 = ggplot2)
    if (requireNamespace("ggthemes", quietly = TRUE)) {
        ggthemes <- c("base", "calc", "economist", 
            "economist_white", "excel", "few", 
            "fivethirtyeight", "foundation", "gdocs", 
            "hc", "igray", "map", "pander", 
            "par", "solarized", "solarized_2", 
            "solid", "stata", "tufte", "wsj")
        ggthemes <- ggthemes[check_theme_exist(ggthemes, package = "ggthemes")]
        if (length(ggthemes) > 0) {
            ggthemes <- setNames(as.list(paste0("ggthemes::theme_", 
                ggthemes)), ggthemes)
            themes$ggthemes <- ggthemes
        }
    }
    if (requireNamespace("hrbrthemes", quietly = TRUE)) {
        hrbrthemes <- c("ft_rc", "ipsum", "ipsum_ps", 
            "ipsum_rc", "ipsum_tw", "modern_rc")
        hrbrthemes <- hrbrthemes[check_theme_exist(hrbrthemes, 
            package = "hrbrthemes")]
        if (length(hrbrthemes) > 0) {
            hrbrthemes <- setNames(as.list(paste0("hrbrthemes::theme_", 
                hrbrthemes)), hrbrthemes)
            themes$hrbrthemes <- hrbrthemes
        }
    }
    return(themes)
}
<bytecode: 0x000001ac20da2030>
````````````

**Comment by opendatasurgeon** [comment]
@sajjadasaf , I believe you're missing `hrbrthemes` here. Please download that package. Also make sure to explicitly load these packages in your app/rmarkdown (if you're missing, then download them)-

````r
    library(esquisse)
    library(rvg)
    library(officer)
    library(hrbrthemes)
    library(ggthemes)
    library(ggplot2)
    library(svglite)
````

Let me know if this works. And if the problem gets solved, please close the issue :)
