### ISSUE TITLE
Misconfigured window

### ISSUE THREAD

**Issue by jrojasquiroz** [dreamRs/esquisse#138]
Hi, 
I installed the package with no problems. But when I try to manipulate data with the 'ggplot2 builder' the window appears misconfigured - so I can not use the Fill, Color or Size tabs.
![esquisseproblem2](https://user-images.githubusercontent.com/34352451/108561931-0d2f5500-72cd-11eb-966c-8681dfafa012.jpg)

Previously, there was another problem that I could solve but maybe is related to this one: When I open the 'ggplot2 builder', the window doesn't allow me to open any dataframe. I mean, there is nothing to click on at the rigth side of the section "Choose a data.frame" (I have had a data frame loaded). Anyway I could solve it using the command line `esquisse::esquisser(The name of my data frame)`.
![esquisseproblem](https://user-images.githubusercontent.com/34352451/108561884-f7219480-72cc-11eb-9c0b-83b315fac545.jpg)

I would like to know if there is a way to solve the misconfigured window. 
In case is useful, my RStudio version is 1.1.463 and my R version is 4.0.2 (2020-06-22).
Thanks for your work.

**Comment by pvictor** [comment]
Thanks for the report, I'll look into this. You can try to update Rstudio if you can, it might help.

Victor

**Comment by jrojasquiroz** [comment]
Dear Victor,
In fact, updating RStudio was the solution. Thanks!
