### ISSUE TITLE
Allowing geom_point when plotting Time vs Continuous Data

### ISSUE THREAD

**Issue by matton2** [dreamRs/esquisse#139]
Hello.  I would like to be able to use geom_point when plotting Time vs Continuous data.  

I attempted to create a branch to implement but am not allowed to branch.

**Comment by pvictor** [comment]
Yes I will add that !

If you want to contribute you can fork this repo then create a pull request.
Note that development of the next version is in branch "dev", so you have to start from there and create a PR in this branch.

Victor

**Comment by matton2** [comment]
Hi @pvictor I will do that.  I should have the request up pretty quickly.

**Comment by matton2** [comment]
I created a PR but not positive i did it correctly....sorry!

**Comment by pvictor** [comment]
It is now available in the GitHub version and will be released on CRAN soon, please re-open this issue if you encounter any trouble.
