### ISSUE TITLE
Is it possible to update the default values ?

### ISSUE THREAD

**Issue by andirey** [dreamRs/esquisse#141]
Is it possible to update the default values, either for the columns that show up in each of the dimension boxes (X, Y, Fill, and etc.) or for the filtered values in the 'Data' pop-up at the bottom?

**Comment by pvictor** [comment]
Hello,

In next version it will be possible to choose between a list of aesthetics to use, what do want to see there ?

For filters, there's only the possibility to display them for all variables or to disable it.

Victor

**Comment by andirey** [comment]
Thank you, Victor!
Will be waiting.
Andrii
