### ISSUE TITLE
Aesthetics boxes in wrong place

### ISSUE THREAD

**Issue by ac11ca** [dreamRs/esquisse#146]
esquisse:::esquisser(data_wide) produces:

https://imgur.com/a/mTnDuDm

The aesthetics boxes are located in the place where the graphic gets built. I cannot access the menus at the bottom of the screen or resize the esquisse screen.

(Also, when I click on "Data" I get "No data selected Use a data.frame from user environment" even though the previous image proves there is a data.frame available).

**Comment by pvictor** [comment]
Hello, you should try to upgrade RStudio.

Victor

**Comment by ac11ca** [comment]
That solved it. Thanks!
