### ISSUE TITLE
Is the sf graphic type working already?

### ISSUE THREAD

**Issue by kweinert** [dreamRs/esquisse#147]
Hi, I recently found this amazing package and I am delighted. However, I could not get the sf graphic type working. When I read an sf object using sf::read_sf and than start esquisser(), the loaded dataset is not available in the data dropdown menu. I skimmed through the source code but I could not really understand how the charts are produced.

Is sf supported already?

Update:
Using sf::st_read instead of sf::read_sf, the dataset actually appears in the data dropdown menu. However, I still cannot produce a chart, the sf icon is always deactivated.

Kind regards from Berlin
Karsten

**Comment by pvictor** [comment]
Hello,

Yes there was some bugs, you need to install dev version of esquisse and datamods to make it work: 

```r
remotes::install_github("dreamRs/datamods")
remotes::install_github("dreamRs/esquisse")

library(sf)
nc <- st_read(system.file("shape/nc.shp", package="sf"))
esquisse::esquisser(nc)
```

This should display: 

![image](https://user-images.githubusercontent.com/4415580/114568561-85364d80-9c74-11eb-8c64-27103e6bdfa4.png)

I have only tested simple choropleth maps, let me know how it works for you and how you want to use `sf` here.

Victor

**Comment by kweinert** [comment]
Works great, thanks! Awesome package!
