### ISSUE TITLE
Problems Launching 

### ISSUE THREAD

**Issue by nffarabaugh** [dreamRs/esquisse#15]
The add-in won't launch for me either when trying to open from the menu  of Rstudio:

> esquisse:::esquisser()
Error in match.arg(arg = status, choices = c("default", "primary", "success",  : 
  'arg' should be one of "default", "primary", "success", "info", "warning", "danger"

I have the same issue when trying to launch directly from the code: 
> esquisse::esquisser()
Error in match.arg(arg = status, choices = c("default", "primary", "success",  : 
  'arg' should be one of "default", "primary", "success", "info", "warning", "danger"

I have tried typing the suggested arguments i.e. (arg = default, or "default") as well as specifiying a data frame i.e ( esquisse::esquisser(data = my.dataframe) and the program still fails to launch giving one of the following errors: 

Error in esquisse::esquisser(defult) : object 'defult' not found

Error in esquisse::esquisser(arg = "default") : unused argument (arg = "default")

Error in match.arg(arg = status, choices = c("default", "primary", "success",  :  'arg' should be one of "default", "primary", "success", "info", "warning", "danger"

Any ideas?

**Comment by pvictor** [comment]
Thanks for reporting. Which version of `shinyWigdgets` have you ?
I think the problem is due to an outdated version, can you update your installed packages and try re-installing ? I need to put a minimum version required.

Victor

**Comment by nffarabaugh** [comment]
Thanks for the prompt response. I have version 0.4.0 of shinyWidgets. There is indeed an updated version (0.4.3). So you are likely correct to think that is the issue. However, I am unable to confirm. For some reason I am having trouble downloading the update as my computer doesn't seem to want to download from source, and the update is not available from binaries.

**Comment by pvictor** [comment]
That's weird, which CRAN mirror do you use ? Binaries have been built, this should work:

````r
install.packages("shinyWidgets", repos = "https://cran.rstudio.com/")
```

Thanks for providing your version number, I'll put `shinyWidgets (>0.4.0)` in DESCRIPTION.

**Comment by nffarabaugh** [comment]
I managed to download the update after some finagling, and the problem resolved. Thanks for your help!
