### ISSUE TITLE
[Feature Request] Linear Trend Line

### ISSUE THREAD

**Issue by p-schaefer** [dreamRs/esquisse#152]
Would it be possible to add an option for linear trend lines as well as the default?

**Comment by pvictor** [comment]
Something with the `method` argument ? Like:

```r
library(ggplot2)
ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)
```
I'll look into it

**Comment by p-schaefer** [comment]
Yes, exactly. Thank you!

**Comment by p-schaefer** [comment]
Any progress on this?

**Comment by pvictor** [comment]
Sorry, not yet! I put it on my todo

**Comment by pvictor** [comment]
If you reinstall from GitHub, you can change smoothing method.
