### ISSUE TITLE
External data gives error: "Error : object 'imported_data' not found!"

### ISSUE THREAD

**Issue by psolymos** [dreamRs/esquisse#154]
Hi! Thanks for this wonderful tool. I am experiencing issues with copy/paste, external file upload, and Google sheets. Only the 'Environment' (R data sets) option is working. I used different data sets and it is always the same error.

1. The data shows up fine in the modal.
2. The column names show up fine in the dragula element.
3. Once I drag the column names to X and Y etc I get the error: "Error : object 'file_name' not found!" (file name being iris.csv etc).

Try `write.csv(iris, row.names=FALSE, file="iris.csv")` with external file upload.

I am using esquisse_1.0.1.9000 and shiny_1.6.0.

I could trace it back to `safe_ggplot()` called by `esquisse_server()`, but had no luck with further troubleshooting.

See below some screen shots:
<img width="1080" alt="Screen Shot 2021-04-21 at 9 46 04 PM" src="https://user-images.githubusercontent.com/831636/115653849-2d8b8800-a2ed-11eb-9566-b7b5ec2e21f6.png">
<img width="1080" alt="Screen Shot 2021-04-21 at 9 46 17 PM" src="https://user-images.githubusercontent.com/831636/115653859-3419ff80-a2ed-11eb-8fd1-e5e8cbd3ea26.png">
<img width="1079" alt="Screen Shot 2021-04-21 at 9 46 30 PM" src="https://user-images.githubusercontent.com/831636/115653868-3714f000-a2ed-11eb-91ef-423e25e7555d.png">

**Comment by pvictor** [comment]
Thanks for reporting this, should be fixed if you re-install datamods and esquisse from GitHub:

```r
remotes::install_github("dreamRs/datamods")
remotes::install_github("dreamRs/esquisse")
```

Victor

**Comment by psolymos** [comment]
Thanks @pvictor for the fix! I can confirm that it resolves the issue.
