### ISSUE TITLE
Language support?

### ISSUE THREAD

**Issue by tvedebrink** [dreamRs/esquisse#155]
First of all great work and impressive UI experience! It puts the power of ggplot2 at the fingertips/cursor of novices.
I would very much like to include your work in some teaching materials to Danish school children where I preferably would like to control the language of the various controls and placeholders. 
If I include esquisse in a Shiny app - which functions/arguments would I need to overwrite locally?
Thanks and best wishes,
Torben

**Comment by pvictor** [comment]
Hello,

Thank you very much for your kind words!
Yes internationalization is in the road map, currently only modules to import data support it (https://dreamrs.github.io/datamods/articles/i18n.html). If you want to add Danish for these modules you can submit a PR by adding a file like this one for french: https://github.com/dreamRs/datamods/blob/master/inst/i18n/fr.csv

For esquisse, the only way currently is to fork the repo and to modify the labels in `R/` directory then rebuild the package. Labels ares mostly in : 
* controls module: https://github.com/dreamRs/esquisse/blob/master/R/module-controls.R
* esquisse module: https://github.com/dreamRs/esquisse/blob/master/R/esquisse-ui.R & https://github.com/dreamRs/esquisse/blob/master/R/esquisse-server.R
* Settings: https://github.com/dreamRs/esquisse/blob/master/R/settings.R

Victor

**Comment by tvedebrink** [comment]
Excellent! I'll take a look at this. For `datamods` your solutions seems very close to plug-and-play - perfect!
I'll try to locate the labels in the suggested files for `esquisse` and rebuild locally. 
Thanks for the swift feedback!

**Comment by pvictor** [comment]
With last release on CRAN, the same mechanism as in datamods is available for esquisse.
If you want a specific language to be available directly in the package, you can submit a PR adding a CSV like this one : https://github.com/dreamRs/esquisse/blob/master/inst/i18n/fr.csv

Victor
