### ISSUE TITLE
code for data updates can save ?

### ISSUE THREAD

**Issue by jixing475** [dreamRs/esquisse#157]
Hello, is it possible to export the code for data updates?

**Comment by issactoast** [comment]
Hi, I have the same question with jixing475, how can i export the data manipulating code from the package?

**Comment by pvictor** [comment]
You refer to converting a variable from a class to another or changing variable name ?
Currently code for this transformations isn't generated.
Now this module live in package [datamods](https://github.com/dreamRs/datamods), so you can open issue / request feature there.

Victor
