### ISSUE TITLE
Bring back the Play/Pause feature

### ISSUE THREAD

**Issue by jfunction** [dreamRs/esquisse#159]
Thanks for the amazing work on this library. I use it frequently and have brought my colleagues on board also! 

I miss the feature where you can prevent esquisse from plotting while you are busy dragging things to build up your plot. Is there a way to bring it back? I refer to the button which used to sit under the "Facet" box at the top which was a green triangle saying "Play". When you clicked it, the plot wouldn't update until you clicked "Pause". 

Am I right that this feature was removed rather than just moved? Is there a way to still use it? It is very useful for plots with lots of data that take a while since stacking up many actions means the user waits a much longer time than needed.

**Comment by pvictor** [comment]
Ahaha yes I removed it, I thought nobody understood what it was for...
I'll see to put it back

Victor

**Comment by jfunction** [comment]
Wonderful! Thank you. I really enjoy esquisse, it has saved me a lot of time, so thank you!

**Comment by pvictor** [comment]
Available in v1.1.1 on CRAN
