### ISSUE TITLE
"Error: object [...] not found"

### ISSUE THREAD

**Issue by Karim-Claudio** [dreamRs/esquisse#169]
Hello,

Thank you for this package, I've been using it for some weeks and it's really helpful.
However, I'm facing an issue when I use imported data, the object containing my dataframe is not found by the app. I've been testing the example provided in the help (the one with data import function), and I get the same error:

![image](https://user-images.githubusercontent.com/15357973/123061089-e4b39500-d43d-11eb-8375-9bc23c719977.png)

As you can see, the file (csv file containing the _mtcars_ dataframe) is properly read by the app but somehow I got this error. I'm not sure if that comes from the file itself, as I've been testing on different datasets.
I'd really appreciate your help on this issue.

Kindly,
Karim

**Comment by pvictor** [comment]
Hello,

Sorry for that, can you try by installing esquisse and datamods from GitHub:

````r
remotes::install_github("dreamRs/datamods")
remotes::install_github("dreamRs/esquisse")
```

Let me know if the bug persist.

Victor

**Comment by Karim-Claudio** [comment]
That works perfectly thank you (sorry I've just realized your answer the same issue on gitmemory.com).
Thank you for the quick answer ^^

Karim

**Comment by pvictor** [comment]
You're welcome, I'll need to push that fix on CRAN, I'm running late 😛
