### ISSUE TITLE
viewer window problem

### ISSUE THREAD

**Issue by jenrichmond** [dreamRs/esquisse#17]
I am trying to use esquisse but the viewer window seems to not display everything. I can't see the labels on the boxes that you drag variables into and my graph doesn't display. 

The viewer panel doesn't seem to expand 

<img width="1280" alt="screenshot 2018-10-03 09 25 44" src="https://user-images.githubusercontent.com/40267093/46382498-9343a480-c6ee-11e8-8898-df3b7b6c02bc.png">

thanks
Jenny

**Comment by pvictor** [comment]
Mmmh that's weird... Which version of RStudio do you use ? (Help > About RStudio)

In the meantime, to try the addin you can launch in your browser with : 

```r
esquisse::esquisser(iris, viewer = "browser")
```

To make the browser as default display mode, you can use this in your Rprofile : 

```r
options("esquisse.display.mode" = "browser")
```

Victor

**Comment by jenrichmond** [comment]
Version 1.1.383

Ah yes, it works perfectly in the browser, just not when I choose ggplot
Builder from the Addins pull down menu. Thanks foe solution
Jenny

**Comment by kenujen** [comment]
I have the same issues on windows10, R 3.5.1, esquisse 0.1.6.
Sometimes I can see flashes of the preview, like when I closed the shiny app.
-Ken

**Comment by fapppian** [comment]
> Mmmh that's weird... Which version of RStudio do you use ? (Help > About RStudio)
> 
> In the meantime, to try the addin you can launch in your browser with :
> 
> ```r
> esquisse::esquisser(iris, viewer = "browser")
> ```
> 
> To make the browser as default display mode, you can use this in your Rprofile :
> 
> ```r
> options("esquisse.display.mode" = "browser")
> ```
> 
> Victor

I have the same problem and tried it in 5 different browsers but still no preview.
I'm on windows 10, version 1.1.463.
Any other ideas?

- Fap

**Comment by pvictor** [comment]
Hi!
Can you provide your `devtools::session_info() ` please?

Victor

**Comment by fapppian** [comment]
> devtools::session_info()
- Session info --------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 os       Windows >= 8 x64            
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United Kingdom.1252 
 ctype    English_United Kingdom.1252 
 tz       Europe/Berlin               
 date     2018-11-08                  

- Packages ------------------------------------------------------------------------------------------------------------
 package     * version date       lib source        
 assertthat    0.2.0   2017-04-11 [1] CRAN (R 3.5.1)
 backports     1.1.2   2017-12-13 [1] CRAN (R 3.5.0)
 base64enc     0.1-3   2015-07-28 [1] CRAN (R 3.5.0)
 bindr         0.1.1   2018-03-13 [1] CRAN (R 3.5.1)
 bindrcpp      0.2.2   2018-03-29 [1] CRAN (R 3.5.1)
 callr         3.0.0   2018-08-24 [1] CRAN (R 3.5.1)
 cli           1.0.1   2018-09-25 [1] CRAN (R 3.5.1)
 colorspace    1.3-2   2016-12-14 [1] CRAN (R 3.5.1)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.5.1)
 data.table    1.11.8  2018-09-30 [1] CRAN (R 3.5.1)
 desc          1.2.0   2018-05-01 [1] CRAN (R 3.5.1)
 devtools      2.0.1   2018-10-26 [1] CRAN (R 3.5.1)
 digest        0.6.18  2018-10-10 [1] CRAN (R 3.5.1)
 dplyr         0.7.7   2018-10-16 [1] CRAN (R 3.5.1)
 fs            1.2.6   2018-08-23 [1] CRAN (R 3.5.1)
 ggplot2       3.1.0   2018-10-25 [1] CRAN (R 3.5.1)
 glue          1.3.0   2018-07-17 [1] CRAN (R 3.5.1)
 gtable        0.2.0   2016-02-26 [1] CRAN (R 3.5.1)
 htmltools     0.3.6   2017-04-28 [1] CRAN (R 3.5.1)
 htmlwidgets   1.3     2018-09-30 [1] CRAN (R 3.5.1)
 httr          1.3.1   2017-08-20 [1] CRAN (R 3.5.1)
 jsonlite      1.5     2017-06-01 [1] CRAN (R 3.5.1)
 lazyeval      0.2.1   2017-10-29 [1] CRAN (R 3.5.1)
 magrittr      1.5     2014-11-22 [1] CRAN (R 3.5.1)
 memoise       1.1.0   2017-04-21 [1] CRAN (R 3.5.1)
 munsell       0.5.0   2018-06-12 [1] CRAN (R 3.5.1)
 pillar        1.3.0   2018-07-14 [1] CRAN (R 3.5.1)
 pkgbuild      1.0.2   2018-10-16 [1] CRAN (R 3.5.1)
 pkgconfig     2.0.2   2018-08-16 [1] CRAN (R 3.5.1)
 pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.5.1)
 plotly        4.8.0   2018-07-20 [1] CRAN (R 3.5.1)
 plyr          1.8.4   2016-06-08 [1] CRAN (R 3.5.1)
 prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.5.1)
 processx      3.2.0   2018-08-16 [1] CRAN (R 3.5.1)
 ps            1.2.1   2018-11-06 [1] CRAN (R 3.5.1)
 purrr         0.2.5   2018-05-29 [1] CRAN (R 3.5.1)
 R6            2.3.0   2018-10-04 [1] CRAN (R 3.5.1)
 Rcpp          0.12.19 2018-10-01 [1] CRAN (R 3.5.1)
 remotes       2.0.2   2018-10-30 [1] CRAN (R 3.5.1)
 rlang         0.3.0.1 2018-10-25 [1] CRAN (R 3.5.1)
 rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.5.1)
 rstudioapi    0.8     2018-10-02 [1] CRAN (R 3.5.1)
 scales        1.0.0   2018-08-09 [1] CRAN (R 3.5.1)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.5.1)
 tibble        1.4.2   2018-01-22 [1] CRAN (R 3.5.1)
 tidyr         0.8.2   2018-10-28 [1] CRAN (R 3.5.1)
 tidyselect    0.2.5   2018-10-11 [1] CRAN (R 3.5.1)
 usethis       1.4.0   2018-08-14 [1] CRAN (R 3.5.1)
 viridisLite   0.3.0   2018-02-01 [1] CRAN (R 3.5.1)
 withr         2.1.2   2018-03-15 [1] CRAN (R 3.5.1)
 yaml          2.2.0   2018-07-25 [1] CRAN (R 3.5.1)

**Comment by pvictor** [comment]
After having launched the add-in please 🙂

**Comment by spyrosRb** [comment]
Hi everyone,

I am trying to incorporate the esquisse shiny module within a shinydashboard by using the code provided below but the plot preview doesn't render.  I speculate that this is a R version compatibility issue.  The code stopped working once updated in R3.5.1, it was working fine before when I was using R3.4.4.

library(shiny)
library(ggplot2)
library(esquisse)
library(shinydashboard)

ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody(
    
    radioButtons(
      inputId = "data",
      label = "Data to use:",
      choices = c("iris", "mtcars"),
      inline = TRUE
    ),
    
    
    tags$div(
      style = "height: 700px;", # needs to be in fixed height container
      esquisserUI(
        id = "esquisse",
        header = FALSE, # dont display gadget title
        choose_data = FALSE # dont display button to change data
      )
    )
    
    
  )
)


server <- function(input, output,session) {
  data_r <- reactiveValues(data = iris, name = "iris")

  
  observeEvent(input$data, {
    if (input$data == "iris") {
      data_r$data <- iris
      data_r$name <- "iris"
    } else {
      data_r$data <- mtcars
      data_r$name <- "mtcars"
    }
  })
  
  callModule(module = esquisserServer, id = "esquisse", data = data_r)
  
}

shinyApp(ui, server)

**Comment by pvictor** [comment]
There was a bug with Shiny last release (1.2.0), try upgrading esquisse. Otherwise, please open a new issue and include the output of `sessionInfo()`.

Victor

**Comment by spyrosRb** [comment]
Hi Victor
Thanks a lot for your response.
I updated the esquisse package and now works like a charm !!!

Spyros

**Comment by rismis** [comment]
<img width="772" alt="Capture" src="https://user-images.githubusercontent.com/102413477/163008944-b1525b4e-67b4-4402-b61f-36aac6dcd2e1.PNG">
I am facing a similar issue, I have updated r and RStudio but nothing changed.
