### ISSUE TITLE
force plot type instead of auto

### ISSUE THREAD

**Issue by klc123** [dreamRs/esquisse#171]
I would like to be able to force a scatterplot but it seems like auto is the default and the only time that I've been able to access scatterplot/point function is when I have at least two continuous variables. I would like my students to have the option to show all of their data points (scatter with jitter) on top of a boxplot. Is this even possible with esquisse at the moment?

**Comment by pvictor** [comment]
Hello,

Thanks for the suggestions. In next CRAN release (or with GitHub version), you will be able to:

* use `geom_jitter()` directly in the geom menu:
![image](https://user-images.githubusercontent.com/4415580/148395971-1929b713-ce75-4f78-881c-9385c26293f2.png)

* add jittered points above a boxplot:
![image](https://user-images.githubusercontent.com/4415580/148396243-a8fdef70-c041-4275-a7b0-cd1972fc1800.png)

Victor
