### ISSUE TITLE
Warning Message in big data sets

### ISSUE THREAD

**Issue by rogerpou** [dreamRs/esquisse#174]
Several windows appear with a message: "Warning: Groups with fewer than two data points have been dropped" when i try to visualize a big data set. I need to infinitely close ALL of this windows every time i do a little change. Maybe just an unique one could be better than one for every time.

**Comment by pvictor** [comment]
Indeed it will be *infinitely* nicer ;)
I put this feature on my TODO, thanks for the feedback !

Victor
