### ISSUE TITLE
package 'esquisse' is not available (for R version 3.4.1)

### ISSUE THREAD

**Issue by chuangys** [dreamRs/esquisse#18]
GREAT tools !! However, I installed fail, is there any specific R support version?

> install.packages("esquisse")
Installing package into ‘C:/Users/bdad2/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘esquisse’ is not available (for R version 3.4.1)

**Comment by pvictor** [comment]
Thanks :)

Should work, Are you behind a proxy ?

**Comment by chuangys** [comment]
No, I'm not behind a proxy. 

> Thanks :)
> 
> Should work, Are you behind a proxy ?

No, I'm not behind a proxy.

**Comment by pvictor** [comment]
I'm not familiar with Microsoft Azure cloud....
That can be a repository issue too, you can check what is your repo with `getOption("repos")` and try to install with : 

```r
install.packages("esquisse", repos = "https://cran.rstudio.com/")
```

**Comment by chuangys** [comment]
> I'm not familiar with Microsoft Azure cloud....
> That can be a repository issue too, you can check what is your repo with `getOption("repos")` and try to install with :
> 
> ```r
> install.packages("esquisse", repos = "https://cran.rstudio.com/")
> ```
Yes, i tried below installation. Then it almost work. 
> install.packages("esquisse",repos="http://cran.us.r-project.org",dependencies=TRUE)

However, still shows another error below.
> library(esquisse)
Error: package or namespace load failed for ‘esquisse’:
 object ‘prettyCheckboxGroup’ is not exported by 'namespace:shinyWidgets'

**Comment by pvictor** [comment]
Oups, problem with shinyWidgets version, you need to update your packages

**Comment by pvictor** [comment]
Did you manage to install the package?
