### ISSUE TITLE
How does the variable geomIcons make its way into esquisserUI.R

### ISSUE THREAD

**Issue by LuptonM** [dreamRs/esquisse#180]
Hi,

This isn't an issue as such. but more of understanding of the package code

In esquisserUI.R, the input$geoms has a argument value geomIcons that doesn't seem to be ever initialised?

Where does geomIcons come from?

KR

Marc

**Comment by pvictor** [comment]
Hello,

`geomIcons()` is a function defined here : https://github.com/dreamRs/esquisse/blob/d650baedbf7d6e5790f0dff717530a46673a626c/R/utils.R#L199
`esquisse:::geomIcons()` returns a named list with HTML tags to show geom icon, and geom's name associated with it. The goal is to construct this menu: 

```r
library(shiny)
library(esquisse)

ui <- fluidPage(
  tags$h2("Drop Input"),
  dropInput(
    inputId = "mydrop",
    choicesNames = esquisse:::geomIcons()$names, 
    choicesValues = esquisse:::geomIcons()$values,
    dropWidth = "220px"
  ),
  verbatimTextOutput(outputId = "res")
)

server <- function(input, output, session) {
  output$res <- renderPrint({
    input$mydrop
  })
}

shinyApp(ui, server)
```
![image](https://user-images.githubusercontent.com/4415580/135867920-916e51ad-2194-4ab9-b9d8-be9fc0bd1cf6.png)

Victor

**Comment by LuptonM** [comment]
Thanks very much. I think I was just being blind searching for that variable
