### ISSUE TITLE
Cyrillic text in plots is not show on PDF export. 

### ISSUE THREAD

**Issue by novica** [dreamRs/esquisse#183]
![118984932-3cd91200-b93b-11eb-9614-48446a949072](https://user-images.githubusercontent.com/165724/137003069-ab048f15-3b58-4247-a24c-2785b9ffa919.png)

When download ggplot as pdf the text is shown as dots (above).

On other apps (not using esquisse) this can be usually solved by using cairopdf. I don't know if that is a possibility with esquisse.

Alternatively I am thinking, it could be a nice workaround to have an option to select which download formats are available.

**Comment by pvictor** [comment]
Ah ok, like this:

```r
ggsave(
  filename = "plot.pdf",
  device = cairo_pdf,
  plot = p,
  dpi = 72,
  width = 800 / 72,
  height = 500 / 72,
  scale = 1
)
```
