### ISSUE TITLE
Toggle control to convert any numeric variable to factor

### ISSUE THREAD

**Issue by khaled-alshamaa** [dreamRs/esquisse#186]
It will be a great feature if we can get a kind of toggle control within the esquisse interface to convert any numeric variable type into a factor (and back to numeric).

**Comment by EDiLD** [comment]
This is possible via the datamods packages on import
https://github.com/dreamRs/esquisse/blob/422e415fbbdb697f40a7f7d0a51378fef47be1cc/R/deprecated.R#L8
