### ISSUE TITLE
Shiny Bookmark not working with dragulaInput

### ISSUE THREAD

**Issue by AndreasUntch** [dreamRs/esquisse#188]
Hello :)

I would like to save the selections made within dragulaInputs during runtime with Shiny Bookmarking state. Unfortunately, it doesn't seem to work. I think it could depend on the random generated ID's for every badge .. As far as I can see, they change with every application restart. 
Is there anything I can do to save selected choices into bookmarks?

Thanks a lot!

Best Regards 
Andreas

**Comment by pvictor** [comment]
Hi,
Yes bookmarking wasn't enabled. If you re-install from GitHub it should work.

Victor
