### ISSUE TITLE
NA are removed in the plugin but not in the code

### ISSUE THREAD

**Issue by sbalci** [dreamRs/esquisse#19]
NA values can be removed from the image on the plugin window
however when I copy the code to the console, the code does not contain information to remove NA. Copied code still produces plot with NAs.

**Comment by pvictor** [comment]
Hi,
There are still some adjustments to be made on the code generated by the filters, it is planned to add it in the next release. I'll keep you posted.

Victor

**Comment by pvictor** [comment]
Code for filters is now available above code for plot.
Please install from GitHub to test before next CRAN release.

Victor
