### ISSUE TITLE
How esquisse work with MySQL or other database together?

### ISSUE THREAD

**Issue by harryprince** [dreamRs/esquisse#190]

**Comment by pvictor** [comment]
Hello,
Currently there's no direct way. You have to retrieve your data with [DBI](https://db.rstudio.com/r-packages/dbi/) before being able to launch esquisse with those.
Creating a module to interface with a database was considered in package [datamods](https://github.com/dreamRs/datamods), but each database has its specificities, so its a little difficult to implement.

Victor
