### ISSUE TITLE
Esquisse language in Albanian

### ISSUE THREAD

**Issue by EGjika** [dreamRs/esquisse#192]
Hi,
I believe there are some words that are not translated properly into the Albanian version of Essquise.   I am a statistician and used esquisse from almost 2 years now with students at university. 
Also the csv file must be saved as : "al" which is the abbreviation of Albania and not "sq" which has nothing to do with Albania.

**Comment by pvictor** [comment]
Hello,
Thank you for your message, would you consider submitting a pull request to correct these problems? That would be very kind of you.
Note that some of the translated labels are located in package {datamods}: https://github.com/dreamRs/datamods
Let me know if I can help you,
Victor
