### ISSUE TITLE
Can't open/load esquisse

### ISSUE THREAD

**Issue by ScarlettEscudero** [dreamRs/esquisse#193]
Hello, I installed esquisse and when I try to open/load it using esquisse:::esquisser() it starts to open but never does and R just stays there for hours "opening" esquisse. There is no error or anything, it just never opens:
![image](https://user-images.githubusercontent.com/47041602/150052780-d4c8bce3-c174-4071-80b5-764cd17faf9f.png)
I already uninstalled it to see, I have an updated version of R and of shiny and shinyWidgets and rtools

**Comment by pvictor** [comment]
Hello,
Mmmh that's weird, what's your RStudio version ? (you can use `sessioninfo::platform_info()` to retrieve it)
Can you try : 
```r
esquisse::esquisser(viewer = "browser")
```
It should launch esquisse in your default browser

**Comment by ScarlettEscudero** [comment]
Thank you for your quick response. I have RStudio Version 4.1.2, I used to have 4.1.0 but I upgraded it thinking that was the problem but it didn't work with neither. 
I tried using the viewer = browser but it doesn't work either, it starts but never opens and R sort of frezzes, I have to terminate by force and shut down R so it can terminate.

**Comment by pvictor** [comment]
Ok, thanks for the informations.
Can you indicate what's your RStudio (the IDE) version ?
You can obtain it like so:

![image](https://user-images.githubusercontent.com/4415580/150177335-17e4d4d9-8972-4799-b9df-71de0273bbf3.png)

![image](https://user-images.githubusercontent.com/4415580/150177436-e13437f6-287a-4328-8bf1-db2d4a18a5d7.png)

**Comment by ScarlettEscudero** [comment]
Hello, it is: Version 1.4.1717
![image](https://user-images.githubusercontent.com/47041602/150177838-e2a6a9aa-962a-410e-a59b-cb88c36cdc27.png)

**Comment by pvictor** [comment]
Thank you!
We use the same version of RStudio and R, so that's not it.
Are you able to launch shiny applications ? For example with:

```r
shiny::runExample("01_hello")
```

what's happening?

**Comment by ScarlettEscudero** [comment]
I think you found the problem. It starts opening but never does, just like when I open esquisse: 
![image](https://user-images.githubusercontent.com/47041602/150179434-2f65e1cd-e8ff-4f2f-912c-813354ffd166.png)

**Comment by pvictor** [comment]
Okay so that's a problem with shiny. You may try to re-install it. The easiest way is to close and re-open RStudio and then run `install.packages("shiny")` (you normally don't need `remove.packages`)

**Comment by ScarlettEscudero** [comment]
Ok, I re-installed it and it still didn't open but I updated every package I had with update.packages(ask = FALSE, checkBuilt = TRUE) and both shiny and esquisse works now!

**Comment by ScarlettEscudero** [comment]
![image](https://user-images.githubusercontent.com/47041602/150184650-f1800443-c3e9-4f87-9a0f-e2afedf382b6.png)
Thank you so much for your help:)

**Comment by pvictor** [comment]
🎉 happy you found a solution! I hope you find esquisse useful!
