### ISSUE TITLE
[Feature Request] Sum for bar charts

### ISSUE THREAD

**Issue by DanielPascoe** [dreamRs/esquisse#198]
Bar charts on a numeric vector seem always to render the counts. Sum would be very useful. Maybe even mean / min / max and other simple measures also, but definitely sum. Seems such a basic thing (so perhaps I have missed it somewhere).

**Comment by paulosouzafmt** [comment]
I repeat the request. In a database, the average in the bar plot would be interesting. I could add a y-transform option that uses the mean with respect to the X-axis items. How about that?

**Comment by pvictor** [comment]
In GitHub version, you can use `stat_summary` in combination of `geom_bar` if you have set `y` aesthetic, e.g.: 

```r
ggplot(mydata, aes(x = x, y = y)) +
  geom_bar(stat = "summary", fun = "mean")
```

For `fun`, you can select between `sum`, `mean`, `max` or `min`.
