### ISSUE TITLE
[Feature Request] Custom calculation column(s)

### ISSUE THREAD

**Issue by DanielPascoe** [dreamRs/esquisse#199]
Nice to have feature rather than a desperately needed one imho but a while back I wrote a shiny app that included a free text box whereby one could add a custom calculated column (I seem to recall I created some custom pseudocode syntax and wrapped the expressions to be evaluated in specific brackets or something like that). I'd have to go back and look at the code. But it was a good, cheap and elegant solution to loads of problems (custom numeric calcs, convert to factor, text substrings, feature creation from multiple columns etc etc). It was basically a swiss army knife and I got good value out of it.

**Comment by pvictor** [comment]
Hello,
This has been added to package [{datamods}](https://dreamrs.github.io/datamods/reference/create-column.html) and available in esquisse through a modal window : 

<img width="898" alt="image" src="https://github.com/dreamRs/esquisse/assets/4415580/3fdd0ce8-3426-4010-868f-a5246d3ab329">

Available on GitHub, soon on CRAN
