### ISSUE TITLE
[Feature Request] Export dragulaInput control type to a separate package

### ISSUE THREAD

**Issue by martinjhnhadley** [dreamRs/esquisse#2]
The dragulaInput control type in the ggplot2 builder interface works very smoothly and would be useful in many other Shiny apps.

Extracting this functionality into a separate dragulaR (for instance) package would be beneficial to the community.

**Comment by pvictor** [comment]
Hi,
Normally I put my custom inputs in [shinyWidgets](https://github.com/dreamRs/shinyWidgets).
In this case, it was easier to develop to have everything in the same package.
But i can move it, no worries.

Victor

**Comment by pvictor** [comment]
There's a whole package dedicated to this Javascript lib : [dragulaR](https://github.com/zzawadz/dragulaR)
