### ISSUE TITLE
Any Spatial Support Offered with this platform ?

### ISSUE THREAD

**Issue by mohammedayub44** [dreamRs/esquisse#20]
Hi,
First of all, this looks pretty awesome tool to quickly build and analyze data sets. Is there any vision down the road to add any spatial map support to this builder. ? Probably an enhancement request.

Thanks !

Mohammed Ayub

**Comment by pvictor** [comment]
Hello,
Thank you for the compliments !
Dev version support `sf` objects, so you can do:

```r
# install dev version
# devtools::install_github("dreamRs/esquisse")
library(sf)
library(rnaturalearth)
wrld <- st_as_sf(countries110)
esquisse::esquisser(wrld)
```
![image](https://user-images.githubusercontent.com/4415580/46580866-57317c00-ca2d-11e8-9256-3ff1a5678d1b.png)

Victor
