### ISSUE TITLE
Not working in R Studio Workbench (former Server Pro) (gray overlay)

### ISSUE THREAD

**Issue by kalaschnik** [dreamRs/esquisse#204]
Hey,

I cannot get esquisse to work within an R Studio Workbench (former R Studio Server) environment. I tried installing the package locally in the user lib and also in the system lib. No difference. There is this gray overlay, and I cannot click any buttons apart from the visualization type. But I cannot select any data to work with... any ideas how to debug this?

https://user-images.githubusercontent.com/9831678/154675357-1eaa617c-67b0-4c5a-bbb2-4c8245acffc4.mp4

**Comment by ncorder-lilly** [comment]
How long are you waiting before exiting the interface? I am experiencing the same grey screen initially, but the new data loader interface appears after waiting (as long as 20 seconds in some instances).

**Comment by kalaschnik** [comment]
I left the tab actively open for a couple of minutes now... the gray overlay is still present and I cannot interact with the UI

**Comment by pvictor** [comment]
Yes something is definetely wrong. Can you try to launch esquisse in a browser's tab to see if the result is the same, with : 

```r
esquisse::esquisser(viewer = "browser")
```

**Comment by kalaschnik** [comment]
Still grayed-out; is there any debug log, I could send?

**Comment by pvictor** [comment]
Mmh weird, is this specific to esquisse ?  can you try both examples below ?

```r
colourpicker:::colourPickerAddin()

# or

library(shiny)
runGadget(
  app = fluidPage(
    tags$h1("HELLO!")
  ), 
  server = function(...) {}, 
  viewer = dialogViewer("Dialog")
)
```

**Comment by kalaschnik** [comment]
Good spot, I get gray overlays also on both of your examples. So not an esquisse issue! I will file an issue in the rstudio repo! Thanks for helping investigating!

**Comment by kalaschnik** [comment]
For reference and help: https://github.com/rstudio/rstudio/issues/3562

**Comment by kalaschnik** [comment]
FYI; We are using Apache and we were missing the `proxy_wstunnel` module. After installing it, shiny apps were not grayed-out anymore. Project sharing also works!
Install the apache module with `sudo a2enmod proxy_wstunnel`
