### ISSUE TITLE
[Improvement suggestions] - Bar charts by means and size of axes

### ISSUE THREAD

**Issue by francielilimab** [dreamRs/esquisse#207]
First, congratulations on the package. 

2 Points that could be seen as improvements:

I) The bar graph adds values ​​for the same x. Could have a transformation by the average number of repetitions.
II) An option to change the size of the x and y axis values, would also be nice option to rotate the x axis values ​​(Angle = 90 for example).

I hope the contribution is useful.

**Comment by pvictor** [comment]
Thanks!

Yes I) is a good suggestion, I think @paulosouzafmt wants the same thing.

For II) yes that should be doable to add some controls, in "Appearance" menu maybe. I'll look into it.

Victor

**Comment by pvictor** [comment]
In GitHub version, you can use `stat_summary` in combination of `geom_bar` if you have set `y` aesthetic, e.g.: 

```r
ggplot(mydata, aes(x = x, y = y)) +
  geom_bar(stat = "summary", fun = "mean")
```

And you can also customize x axis labels (size, fontface, angle...)
