### ISSUE TITLE
dragulaInput providing selected not working

### ISSUE THREAD

**Issue by AndreasUntch** [dreamRs/esquisse#208]
Hello,

for the last weeks I experienced that the functionality of selected isn't working anymore. 
When I provide selected values as named list (targetIds) nothing happens. Is this a known issue?
This seems to appeared around the "bookmarking" commit in January.

Many Thanks

Best regards
Andreas

**Comment by pvictor** [comment]
Indeed, thanks for reporting it. It's fixed in the GitHub version. I'll try to push on CRAN soon.

Victor
