### ISSUE TITLE
Unable to install ESQUISSE on Mac OS 13

### ISSUE THREAD

**Issue by BiotechV** [dreamRs/esquisse#214]
Hi everyone,

I have to come back to R for my internship, and having a lot of tricks to do. I wanted to install SKETCH. However when I try:
```r
install.packages("esquisse")
```
 I get error messages and a failure to install. Precision, I am on MAC OS 10.13.6 and my Rstudio n° 1.2.5001

I hope someone can help me
Thanks in advance
BiotechV

------  

_> install.packages("esquisse")
also installing the dependencies ‘datamods’, ‘shiny’, ‘shinyWidgets’

  There are binary versions available but the source versions are later:
             binary source needs_compilation
datamods      1.2.0  1.3.2             FALSE
shiny         1.6.0  1.7.1             FALSE
shinyWidgets  0.6.2  0.7.0             FALSE
esquisse      1.1.0  1.1.1             FALSE

installing the source packages ‘datamods’, ‘shiny’, ‘shinyWidgets’, ‘esquisse’

essai de l'URL 'https://cran.rstudio.com/src/contrib/datamods_1.3.2.tar.gz'
Content type 'application/x-gzip' length 710197 bytes (693 KB)
=
downloaded 693 KB

essai de l'URL 'https://cran.rstudio.com/src/contrib/shiny_1.7.1.tar.gz'
Content type 'application/x-gzip' length 2963486 bytes (2.8 MB)
==================================================
downloaded 2.8 MB

essai de l'URL 'https://cran.rstudio.com/src/contrib/shinyWidgets_0.7.0.tar.gz'
Content type 'application/x-gzip' length 751613 bytes (733 KB)
==================================================
downloaded 733 KB

essai de l'URL 'https://cran.rstudio.com/src/contrib/esquisse_1.1.1.tar.gz'
Content type 'application/x-gzip' length 2438381 bytes (2.3 MB)
==================================================
downloaded 2.3 MB

* installing *source* package ‘shiny’ ...
** package ‘shiny’ correctement décompressé et sommes MD5 vérifiées
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘Rcpp’ 1.0.2 is being loaded, but >= 1.0.7 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
Exécution arrêtée
ERROR: lazy loading failed for package ‘shiny’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/shiny’
Warning in install.packages :
  installation of package ‘shiny’ had non-zero exit status
ERROR: dependency ‘shiny’ is not available for package ‘shinyWidgets’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/shinyWidgets’
Warning in install.packages :
  installation of package ‘shinyWidgets’ had non-zero exit status
ERROR: dependencies ‘shiny’, ‘shinyWidgets’ are not available for package ‘datamods’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/datamods’
Warning in install.packages :
  installation of package ‘datamods’ had non-zero exit status
ERROR: dependencies ‘datamods’, ‘shiny’, ‘shinyWidgets’ are not available for package ‘esquisse’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/esquisse’
Warning in install.packages :
  installation of package ‘esquisse’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/j3/0225yzqj52s37dvyghjk4dgh0000gn/T/RtmppXxItL/downloaded_packages’_

**Comment by pvictor** [comment]
This seems to be a problem related to an insufficient version number of Rcpp.
Try to restart R, install Rcpp, then install esquisse.
