### ISSUE TITLE
One categorical variable is missing from the Data tab

### ISSUE THREAD

**Issue by jmouchnino** [dreamRs/esquisse#218]
I use this data

```r
library(dplyr)
tuesdata <- tidytuesdayR::tt_load(2022, week = 29)
technology <- tuesdata$technology %>% select(variable, iso3c, year, value) %>% dplyr::slice_sample(n = 30000)

esquisse::esquisser()
```
![image](https://user-images.githubusercontent.com/103758616/180662176-d08a2ee1-1a8c-4503-bd7e-548c805c9015.png) 
![Capture d’écran 2022-07-24 210617](https://user-images.githubusercontent.com/103758616/180662207-020f70ac-830a-4bb0-afd6-bf630932f102.png)

Why are the categorical variables missing from the _Data_ tab ?  I'm sure that once it was possible to filter the categorical variables in the app.

**Comment by jmouchnino** [comment]
The `iso3c` variable doesn't contain unique values only

```r
set.seed(7)
tuesdata <- tidytuesdayR::tt_load(2022, week = 29)
technology <- tuesdata$technology %>% 
  select(variable, iso3c, year, value) %>% 
  dplyr::slice_sample(n = 30000)

technology$iso3c %>% table()
# ABW AFG AGO ALB AND ANT ARE ARG ARM ASM ATA ATG AUS AUT AZE BDI BEL BEN BFA BGD BGR BHR BHS BIH BLM 
# 35  96 129 155  22   3 109 294  71  35   8  59 340 324 105  98 311 121 106 146 195  91  71  77   1 
# BLR BLZ BMU BOL BRA BRB BRN BTN BWA CAF CAN CHE CHL CHN CIV CMR COD COG COK COL COM CPV CRI CSK CUB 

esquisse::esquisser(technology)
```

**Comment by pvictor** [comment]
Ah yes, sorry. If there are more than 50 unique value, the filter isn't generated. Maybe we should reconsider that rule.

**Comment by emilopezcano** [comment]
I would suggest adding an argument to the esquise_server() function and modify the call to filter_data_server() in this line to allow customisation when adding esquisse to shiny apps:

https://github.com/emilopezcano/esquisse/blob/3dc09ef43e97a35292c209917ecf395aecfb5ead/R/module-controls.R#L293C15-L293C15

I will send a pull request for your review
