### ISSUE TITLE
Can't load korean or urdu 

### ISSUE THREAD

**Issue by shahnawaz323** [dreamRs/esquisse#219]
I have tried to load both urdu and korean language language for esquisse by running command 
`set_i18n("ur")` 
`esquisser()`
 but I get the error "Error: i18n option must be either: a list, a data.frame, or a path to a valid file." . For French it's working fine

**Comment by pvictor** [comment]
That's because translations files are missing for package [datamods](https://github.com/dreamRs/datamods) and are needed for modules import and filter data.
I'll find a solution to make it work even with incomplete translations.

Victor

**Comment by shahnawaz323** [comment]
ok thanks. I will generate a pull request for urdu language translation in datamods atleast
