### ISSUE TITLE
Changing i18n after build application not works.

### ISSUE THREAD

**Issue by jhk0530** [dreamRs/esquisse#222]
Hi, thanks for building an awesome package. I use this for my projects and sometimes I use this standalone to custom ggplot figures easier.

---

Here's my problem and what I tried.

I'm building shiny application which can support more than 1 language. (of course with esquisse)

build application with `esquisse_ui` and `esquisse_server`

when the user changes the language option (suppose `input$lang`)

- `set_i18n(input$lang~~)` on server. ( which didn't change language, assume i18n csv file has prepared ) 

- `set_i18n` and re-render `esquisse_ui` and `esquisse_server` with `uiOutput`. (this changes language, but can't build ggplot figure)

---

Here's my question.

Is there any methods to change the language by user's input?

Thanks.

**Comment by jhk0530** [comment]
![esquisse](https://user-images.githubusercontent.com/6457691/186441124-3c225015-4a44-4d52-bf2e-231376b07256.gif)

Here's gif file. for what happen when re-rendering ui & server ( it shows, plot very shortly)

change Title, subtitle will work. but not main plot

**Comment by jhk0530** [comment]
Problem solved.

it seems no need to declare esquisse_server for every update but just for UI.

**Comment by pvictor** [comment]
Nice work. Indeed the server needs to be declared only once.

And the yes, the i18n mechanism is not currently reactive, so it's not possible to switch language inside the app session (except the way you did), an other solution will be to restart the application with `session$reload()` after changing the language.
