### ISSUE TITLE
Bug: insertTab() doesn't work when there is an esquisse module on the page

### ISSUE THREAD

**Issue by daattali** [dreamRs/esquisse#224]
Example:

```r
library(shiny)

ui <- fluidPage(
  tabsetPanel(
    id = "tabs",
    tabPanel("tab1", esquisse::esquisse_ui("test")),
    tabPanel("tab2", "tab2")
  )
)

server <- function(input, output, session) {
  esquisse::esquisse_server("test", data_rv = reactiveValues(data=iris, name="iris"))
  insertTab("tabs", tabPanel("tab3", "tab3"))
}

shinyApp(ui, server)
```

The third tab doesn't work. If you remove the esquisse_ui, then it will work.

If you look at the javascript console, you'll see that there is an error when trying to add a tab with esquisse on the page.

**Comment by pvictor** [comment]
Hi,
That's actually a bug in [shinyWidgets](https://github.com/dreamRs/shinyWidgets), it's fixed if re-install the package from GitHub : 

```r
remotes::install_github("dreamRs/shinyWidgets")
```

Victor

**Comment by daattali** [comment]
Fantastic! I guess I didn't isolate the bug closely enough to see which part exactly was causing the problem, I hope it didn't take you too much time to find the cause and fix. Thanks for the prompt work!
