### ISSUE TITLE
Bug: dynamically inserted esquisse module breaks when "filters" control isn't used

### ISSUE THREAD

**Issue by daattali** [dreamRs/esquisse#225]
When an esquisse module is inserted into a shiny app dynamically -- whether using `insertTab()`, `insertUI()`, or `uiOutput()/renderUI()`, if the "filters" control isn't used then the plot doesn't get generated. The rest of the module seems to work - the code gets updated for example - but the plot breaks. If the "filters" control is used, then it works fine.

Example:

```r
library(shiny)

ui <- fluidPage()

server <- function(input, output, session) {
  insertUI("body", "beforeEnd", esquisse::esquisse_ui("test", controls = c("appearance")))
  esquisse::esquisse_server("test", data_rv = reactiveValues(data = iris, name = "iris"))
}

shinyApp(ui, server)
```

Using {esquisse} 1.1.2 and {shinyWidgets} from latest GitHub

It results in an empty plot:

![image](https://user-images.githubusercontent.com/952340/191537965-19687e08-0ab9-4ad6-aa09-b79bd375e11b.png)

**Comment by pvictor** [comment]
Okay that should be fixed. Please re-install from GitHub : 

```r
remotes::install_github("dreamRs/esquisse")
```

**Comment by daattali** [comment]
Confirm fixed. Thank you!!
