### ISSUE TITLE
Feature request: esquisse_ui(play_pause =FALSE, export = FALSE)

### ISSUE THREAD

**Issue by daattali** [dreamRs/esquisse#226]
A nice-to-have: allow the user to remove the play/pause button and the export button from the plot.  They are both extremely useful features, but there's so much going on in esquisse that sometimes it can be nice to keep it more basic.

**Comment by pvictor** [comment]
Implemented in https://github.com/dreamRs/esquisse/commit/94dc1a07aa289ebd44ff0182aa3e8166eedec377
