### ISSUE TITLE
The same warning should not appear constantly after closing it

### ISSUE THREAD

**Issue by daattali** [dreamRs/esquisse#228]
Using this as an example:

```r
library(shiny)

ui <- fluidPage(
  esquisse::esquisse_ui("test")
)

server <- function(input, output, session) {
  esquisse::esquisse_server("test", data_rv = reactiveValues(data = iris, name = "iris"))
}

shinyApp(ui, server)
```

Place "Sepal.Width" in X and "Species" in size. You'll get a warning:

![image](https://user-images.githubusercontent.com/952340/191555535-b83c870e-2dc6-4693-a60d-098e5e859bca.png)

That's great. It's a useful advise, but I may choose to ignore it. After dismissing the warning, absolutely any further changes I make will keep triggering it every time.

**Comment by pvictor** [comment]
See https://github.com/dreamRs/esquisse/issues/240
