### ISSUE TITLE
Feature request: allow changing height of container, especially important when facets are used

### ISSUE THREAD

**Issue by daattali** [dreamRs/esquisse#229]
The default container is 700px which is a great default. Sometimes a plot may require additional height, for example if there are many y axis labels or facets. It would be nice to have an option, perhaps in the "Appearance" menu, that allows us to dynamically modify the container's height.

I just did a quick hacky test in the chrome devtoolsbar, and it seems that merely changing the height from 700 to any other number "just works".

On a related note, if this would exist, I would maybe want to modify the "plot height" rather than "container height", since the plot height is more meaningful. And I think it might be easily doable, since the height of the rest of the module is fairly static: the header is fixed at 50px, the aes bar is fixed at 160px, and the menus on the bottom are the only thing that's not fixed but they can be pegged to 35px. This means the plot height is always going to be (containerHeight - 160 - 35 - 50*header)

**Comment by ivan-paleo** [comment]
I totally agree with the need for this feature: being able to adjust the size (width and height) of the container window would be great!
