### ISSUE TITLE
How do i get the esquisse package for R3.3.3

### ISSUE THREAD

**Issue by amit27dubey** [dreamRs/esquisse#23]
How do i get the esquisse package for R3.3.3
When i am trying to install the package for esquisse then i m getting below error 

> install.packages("esquisse")
Installing package into ‘C:/Users/Amit/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘esquisse’ is not available (for R version 3.3.3)

**Comment by amit27dubey** [comment]
please let me know do i have to downgrade my r version or some thing else

**Comment by pvictor** [comment]
Do you you now which CRAN repository do you use ? You can try : 

```r
install.packages("esquisse", repos = "https://cran.rstudio.com/")
```

**Comment by amit27dubey** [comment]
Hi Victor, I tried the same but no luck. i am using R version 3.3.3 .

**Comment by amit27dubey** [comment]
Do you want me to uninstall the R and then install the 0.1 version . please let me know . i am new user of R

**Comment by amit27dubey** [comment]
many thanks for your all valuable help and guidance

**Comment by pvictor** [comment]
Mmh weird. No need to downgrade, on the contrary try to install last release : R 3.5.1.
What is the result of the command `sessionInfo()` on the machine you want to install the package on ?

**Comment by HenrikBengtsson** [comment]
Use:
```r
install.packages("esquisse", type = "source")
```
but updating to a modern version of R is a much better solution.

CRAN only builds Windows binaries for the current R version (now R 3.5.z), the developer version (to become R 3.6.0), and the previous release (now R 3.4.z).  When esquisse was first released 2018-09-28, CRAN built Windows binaries for R 3.4.z, R 3.5.z, and R 3.6.0, but nothing before that.  See:

* https://cran.r-project.org/bin/windows/contrib/3.3/
* https://cran.r-project.org/bin/windows/contrib/3.4/
* https://cran.r-project.org/bin/windows/contrib/3.5/
* https://cran.r-project.org/bin/windows/contrib/3.6/

**Comment by pvictor** [comment]
Thank you for the clarification @HenrikBengtsson !

**Comment by amit27dubey** [comment]
Hi pvictor and HenrikBengtsson .......thank you for your help. My issue resolved . 
I am sharing this discussion tag to my other network as well so that they also get benefited by your valuable information and help. Thanks again :+1:
