### ISSUE TITLE
Usability and UI issues when using esquisse with bootstrap5

### ISSUE THREAD

**Issue by daattali** [dreamRs/esquisse#230]
Demo small app:

```r
library(shiny)

ui <- fluidPage(
  theme = bslib::bs_theme(version = 4),
  esquisse::esquisse_ui("test")
)

server <- function(input, output, session) {
  esquisse::esquisse_server("test")  
}

shinyApp(ui, server)
```

The data loading module is especially broken, but the plotting area also has a lot of broken UI. It would be nice if there was a way to include esquisse in a larger shiny app that uses bootstrap4/5

**Comment by pvictor** [comment]
Yes `esquisse_ui` used `shiny::fixedPage` that is only needed in the addin and which comes with its own Bootstrap theme independently of what is used in the page.
It should work now. 
esquisse and datamods should work with Bootstrap 5, but I won't do much for Bootstrap 4 since the default version in bslib is already 5.

**Comment by daattali** [comment]
They do not currently work with bs5.

```r
library(shiny)

ui <- fluidPage(
  theme = bslib::bs_theme(version = 5),
  esquisse::esquisse_ui("test")
)

server <- function(input, output, session) {
  esquisse::esquisse_server("test")  
}

shinyApp(ui, server)
```

A lot of the inputs aren't working, for example the radio buttons for selecting an import method and any of the dropdowns. So it might be a shinyWidgets issue?

![image](https://user-images.githubusercontent.com/952340/191779588-7788cf2c-863c-4b09-9779-323276620660.png)

**Comment by daattali** [comment]
Ah, I didn't understand that you had fixed it today before my last comment! It is functional now!

There are some UI/usability issues with bs5, I'm going to change this issue to be about that. Namely (for each one I have two screenshots, the first is classic and the second is bs5):

**1. The names of the variables are hard to read**


  ![image](https://user-images.githubusercontent.com/952340/191821691-e2e64334-f80b-4fe9-897e-513f09c45a8f.png)

  VS

  ![image](https://user-images.githubusercontent.com/952340/191823709-2b4ffbfe-ec35-448d-81f3-829132017f48.png)


**2. The background of the selected geom is now grey which looks awkward when everything around it is white**

![image](https://user-images.githubusercontent.com/952340/191822447-f1de0eaf-dad9-4ba3-ad3f-771fb83aec0f.png)
    
VS
    
![image](https://user-images.githubusercontent.com/952340/191823877-92a9fd77-4937-47b3-baae-e20d6cff4d71.png)


**3. The tabs on the bottom are impossible to differentiate since the entire row is just one long grey rectangle**

![image](https://user-images.githubusercontent.com/952340/191822568-1a06314c-1597-44d6-9e7b-13763aa5e5a3.png)

VS

    
![image](https://user-images.githubusercontent.com/952340/191824391-80c189c8-5cf8-4be5-92cd-a0aaf6b40ca9.png)


**4. Geoms that are invalid and therefore cannot be selected no longer have a "not-allowed" cursor on hover**

![image](https://user-images.githubusercontent.com/952340/191822366-48234df7-8ef3-4018-be52-421b40083ad8.png)

VS

    
![image](https://user-images.githubusercontent.com/952340/191824725-17955ad6-8096-4086-8c15-1e72797b0fd1.png)


**5. The tabs on the bottom used to always be a consistent height, now they break up into multiple lines which looks worse. It's especially noticeable beause bs5 made the font size larger and there's more whitespace, so this issue happens a lot, even on screens that were wide enough previously**
 
![image](https://user-images.githubusercontent.com/952340/191822649-8b3fb1e8-991f-478d-a20c-572aa8687585.png)

VS

    
![image](https://user-images.githubusercontent.com/952340/191824980-9aa81c9c-7738-4f08-9168-f255bf899d84.png)


**6. "Copy to clipboard" button location and size and look are completely different**

![image](https://user-images.githubusercontent.com/952340/191822937-0e541347-f97a-4c51-92ed-4097a3f1d599.png)

VS

![image](https://user-images.githubusercontent.com/952340/191823617-b10ecd0a-d059-4a0d-a5e5-8ca1ef2f2767.png)


**7. All the options in the export dropmenu are now underlined**

![image](https://user-images.githubusercontent.com/952340/191826834-86e3c6a9-f0a7-4ae8-8af9-c8c556b269b2.png)

VS

![image](https://user-images.githubusercontent.com/952340/191823393-6e7634fe-4d6a-425f-acd4-4b213101834f.png)


**8. "Update preview" button in the export panel is always too big - no matter how wide the browser is, the button takes up two lines**

![image](https://user-images.githubusercontent.com/952340/191826940-66321233-b2fc-4bb1-9e9f-ca8da20fa3c7.png)

VS

![image](https://user-images.githubusercontent.com/952340/191823463-3c79087c-502a-4713-8093-121ec8ab3b2f.png)


**9. Some broken UI with radio buttons in the "Appearance" tab**

![image](https://user-images.githubusercontent.com/952340/191827256-8fd5b7a4-96dc-4a7c-bbd6-2124919965c6.png)

VS

![image](https://user-images.githubusercontent.com/952340/191826124-ec381c18-021a-4799-8da1-6a3dc6174a85.png)


**10. Some other buttons were converted to grey because of bs5 and it would be nicer to explicitly set them to white to have a more consistent look for the whole app. The button for export options is one example, and all the "+" buttons in the labels+title menu is another example**

**Comment by pvictor** [comment]
Sorry, I should have been clearer. Thank you for this very complete list, it will be very useful to me.
In some cases I think I have to do without Bootstrap, like for the variable badges.
For the buttons we have to see, I wanted to touch as little as possible their appearance to let users the possibility later to modify them according to their desire, but I agree that their appearance currently with a BS 5 theme is not terrible.

**Comment by pvictor** [comment]
I'll look in the next week, lot of those seems related to `actionButton` / `actionLink`.
