### ISSUE TITLE
Allow esquisse_server() to be initialized with NULL without forcing the import module to appear

### ISSUE THREAD

**Issue by daattali** [dreamRs/esquisse#232]
The esquisse module seems to always trigger the data import modal if the initial `reactiveValues$data` is `NULL`. I understand the logic behind this and it's a sensible default behaviour, but it would be useful to have the ability to control that. For example, consider the following small app, where I want the user to select a dataset from a list:

```r
library(shiny)

ui <- fluidPage(
  selectInput("dataset", "dataset", c("iris", "mtcars")),
  esquisse::esquisse_ui("test")
)

server <- function(input, output, session) {
  rv <- reactiveValues(data = NULL, name = NULL)
  observeEvent(input$dataset, {
    rv$data <- get(input$dataset)
    rv$name <- input$dataset
  })
  esquisse::esquisse_server("test", rv)
}

shinyApp(ui, server)
```

I don't want to have the import modal show up, I just want the user to select a dataset and then populate esquisse with it.  I know I can get around this by supplying a non-NULL value initially but it would be cleaner if I could tell esquisse to not show the modal.

**Comment by pvictor** [comment]
Using a zero-length data.frame or similar won't show up the import module.
But I unserstand your point, maybe I can use the existing `import_from` argument, something like `import_from = "none"` or `import_from = NULL` will prevent the import modal to show up.
