### ISSUE TITLE
log transformation: + scale_y_log10()

### ISSUE THREAD

**Issue by installingrattle** [dreamRs/esquisse#24]
Thank you for an incredible package.

Any chance we can get 
```
+scale_y_log10()
+scale_x_log10()
```
as options? Thank you

**Comment by itcarroll** [comment]
Began implementing this feature on [itcarroll/esquisse](https://github.com/itcarroll/esquisse/tree/semilog).

<img width="1275" alt="screen shot 2018-10-09 at 10 05 47 pm" src="https://user-images.githubusercontent.com/3383837/46709975-07f97000-cc14-11e8-89bc-e21495826bac.png">

I pulled all the `*_trans` from the "scales" package to populate a new `selectInput` for X and Y in module-chartControls.R. This may be a bit much, and allows transformations that break the plot (but don't crash the app). The "right way" might be to include a possible_trans analagous to possible_geoms ... which might be a lot of work. Thoughts?

**Comment by dan-reznik** [comment]
is it useable? should i install it?

**Comment by itcarroll** [comment]
@dan-reznik Sure, the fork is working as described. I moved it though, so install with `devtools::install_github('sesync-ci/esquisse@semilog')`.
