### ISSUE TITLE
Feature request: ability to not show warnings

### ISSUE THREAD

**Issue by daattali** [dreamRs/esquisse#240]
The warning alerts in the bottom right corner can become very annoying if they are too frequent. As an example, the `penguins` dataset from {palmerpenguins} seems to cause warnings all the time. If you just load the dataset and add any of the numeric variables to the X variable, you get a warning. Then no matter what else you do afterwards, that warning keeps popping up every time. 

Related to #228

**Comment by pvictor** [comment]
You can hide notifications from esquisse in CSS with `div[id^="shiny-notification-esquisse"] {display: none;}`.

**Comment by daattali** [comment]
Thanks, I have been using that as a workaround :)

**Comment by yfu-caredx** [comment]
I'm a new user trying to following the penguin example. The repeating warnings are definitely most annoying. It would be good to add an option in the esquisser() call to ignore all warnings in the UI.

**Comment by pvictor** [comment]
Warning messages are now displayed only once per session, and the user can choose via the settings menu not to display them at all. If you're using the `esquisse_server()` module, there's a new `notify_warnings =` argument for choosing what to do with notifications: display them all, only once per warning or never display them at all.
