### ISSUE TITLE
Question about the data security

### ISSUE THREAD

**Issue by XuejingJiang** [dreamRs/esquisse#241]
First, I would like to thank you so much for building such a great interactive tool that makes data visual exploration so easy for both beginners and advanced ggplot users! Especially, it's so time-efficient that changing some very specific parameters of the plot can be as simple as click a few checkbox or sliders, and we can insert the script in the end. 

I just have one question about the data security since I deal with sensitive personal data on daily basis, and it is so important to make sure the data is secure. I tried to go through the esquisser() and esuisse_server() scripts and the message "Listening on http://127.0.0.1:7877" when running my data in esquisser function. But my programming and server knowledge is very limited, and it is so hard for me to get answer on my own. Could you please provide insights about where the data is processed when executing the function? Is the data uploaded to some external server, or remained securely and privately my PC/local server?

Thank you so much! 

![image](https://user-images.githubusercontent.com/44414852/208720892-b222aa13-150e-4463-a203-32e7ad2ca797.png)

**Comment by pvictor** [comment]
Hello,

Data is processed on your machine, like when you use any other R function. http://127.0.0.1 is the localhost and refer to your own machine, the one where you installed R. Don't worry data isn't uploaded anywhere by esquisse.

Victor

**Comment by XuejingJiang** [comment]
Thank you for clarification, Victor!
