### ISSUE TITLE
[Feature Request] Grouping / Position option

### ISSUE THREAD

**Issue by jhk0530** [dreamRs/esquisse#242]
Thanks for the nice application 🤗

### **I want to**
I tried to make a **dodge barplot** like the below Image.

<img src="https://user-images.githubusercontent.com/6457691/210466086-d8d1593c-64b1-44c6-8f33-c9dfda765953.png" width = '400'>

### **Situation**
However, when plot is a histogram, it didn't give option to select Position 

<img width="400" src="https://user-images.githubusercontent.com/6457691/210466323-63904927-e5ad-46db-9e89-a0b8f665ff39.png">

<img width="400" src="https://user-images.githubusercontent.com/6457691/210466541-25b3fa50-13a4-4a06-89a4-a15267a24b64.png">

### **Possible solution**

I found simillar issue (#32), which added position to line plot. 

So add `position option` to this chart may work.

Thanks !

**Comment by pvictor** [comment]
Hello,
Thanks for the examples. If you re-install from GitHub you can use position widget with histograms.

Victor

**Comment by jhk0530** [comment]
Hi,

As re-install from github. it works.

Thanks !

Kim
