### ISSUE TITLE
UI issues in Shiny app

### ISSUE THREAD

**Issue by valcaras** [dreamRs/esquisse#243]
Hi! 
I try to use esquisse module in a Shiny app with css style. When it is run graphs options are not displayed fully.

Parts of code:
```
 tabPanel("Make your plot",
                  fluidRow(
                    esquisse_ui( 
                     id = "esquisse",
                     container = esquisseContainer(),
                     header = FALSE)
                 ))

observeEvent(input$tabs_set, {
  if(input$tabs_set == "Make your plot") {
    esquisse_server(
      id = "esquisse",
      data_rv = NULL,
      default_aes = c("fill", "color", "size", "group", "facet"),
      import_from = c("env", "file", "copypaste", "googlesheets")
    )
  }   
})
```

![Screenshot 2023-01-12 at 14 01 02 (2)](https://user-images.githubusercontent.com/100769757/212062157-d28954b4-b6a3-4891-92cc-7b76d097ac6b.png)

**Comment by pvictor** [comment]
Please share more of your code, you seems to be using a custom theme for example.
And you can also try to use last version on GitHub, many changes have been made here.
