### ISSUE TITLE
Esquisse creates duplicate IDs / invalid HTML

### ISSUE THREAD

**Issue by daattali** [dreamRs/esquisse#244]
Running a simple esquisse example:

```r
library(shiny)

ui <- fluidPage(
  esquisse::esquisse_ui("test")
)

server <- function(input, output, session) {
  esquisse::esquisse_server("test", data_rv = reactive(mtcars), import_from = NULL)
}

shinyApp(ui, server)
```

This creates (at least) two sets of elements that share an ID. There are two elements with ID `test-controls-fill_color` and two elements with ID `test-controls-color_ribbon`. You can verify this by running in the javascript console: `document.querySelectorAll("#test-controls-color_ribbon")`

There should not be any element on the page with a duplicate ID

**Comment by pvictor** [comment]
Thanks for reporting, an issue in `shinyWidgets::colorPickr()`, should be fixed now.

Victor
