### ISSUE TITLE
Update ReadMe with German i18n

### ISSUE THREAD

**Issue by M-Colley** [dreamRs/esquisse#252]
There already is the [German translation](https://github.com/dreamRs/esquisse/blob/master/inst/i18n/de.csv). The German flag is available [here](https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Germany.svg) as an .svg.

Thank you very much for this package!

Kind regards

**Comment by pvictor** [comment]
Yes done! Thx
