### ISSUE TITLE
Opcion barra lateral al inferior

### ISSUE THREAD

**Issue by JoseVeraReyes** [dreamRs/esquisse#253]
![image](https://user-images.githubusercontent.com/69726941/229439137-81ddc096-0687-4049-92b6-735374c8b000.png)

existe una forma de hacer que la barra lateral de labels, options y export, se pueda poner debajo o encima de los graficos.

**Comment by JoseVeraReyes** [comment]
o al menos que se pueda poner asi :

![image](https://user-images.githubusercontent.com/69726941/229440171-d8c6ccbc-7b11-4f08-9630-1db4b44ef2a0.png)

esto solo con respecto a la barra lateral

**Comment by pvictor** [comment]
Can you provide a reproducible example so I can check what's going wrong ?
