### ISSUE TITLE
What about adding geom_path to Esquisse?

### ISSUE THREAD

**Issue by PaulinoMF** [dreamRs/esquisse#256]
Perhaps it is my fault but I cannot find an option to draw and configure geom_path. If it is already in the package and I could not find it, please forgive me. If not, why not enhance the package with this addition?

Another solution could be make all the configuration with geom_line and the change it in the code once it is everything configured but I think it would be much better if this type of geometry was included in the package.

**Comment by pvictor** [comment]
Hello,

Yes I added `geom_path` in the list of available geoms, let me know if it suits your needs.

Victor

**Comment by PaulinoMF** [comment]
Sure, that's it. Thanks so much, Victor. Congratulations for your work!!!
