### ISSUE TITLE
Error when trying to execute the 'ggplot2' builder Addin.

### ISSUE THREAD

**Issue by Galozaurus** [dreamRs/esquisse#27]
When trying to execute the Addin:
```
Error in if (is.null(data) && defaultData %in% ls(pos = globalenv())) { : 
  missing value where TRUE/FALSE needed
```

The export to PowerPoint Addin seems to execute just fine.

**Comment by pvictor** [comment]
Hi,
I think that's the same issue as #25 . It only occurs when no tabs are open in RStudio. This is fixed in dev version.

Victor
