### ISSUE TITLE
Allow specifying shape as an aesthetic

### ISSUE THREAD

**Issue by vikasrawal** [dreamRs/esquisse#274]
I have just started exploring esquisse and find it very useful.  I find that I cannot specify shape as an aesthetic while making a scatter plot. That should be a very common use case to differentiate points for different categories by shape. 

Hence this feature request.

**Comment by jonovik** [comment]
For anyone else coming here: The way to map a variable to the shape aesthetic is to:

1. Click the gear icon at top right of esquisse, just left of the closing X.
2. Check "shape" and any other options you would like to have. (Note "group" especially: It is shown by default, but is unchecked when you click the gear icon. Seems like a small bug in today's CRAN and GitHub versions both.)
3. Profit!
