### ISSUE TITLE
esquisse window crashing while starting

### ISSUE THREAD

**Issue by nitin194** [dreamRs/esquisse#28]
First of all many thanks for creating such an awesome tool. I would love to use it for my data related tasks 

I was trying my hands on with the esquisse package but it's crashing every time I try to execute it. below is the console output details:

#####################################################

library(esquisse)
data = read.csv("iris.csv")
esquisse::esquisser(data)
Loading required package: shiny

Listening on http://127.0.0.1:6376
Warning: Error in observeEvent: unused argument (ignoreInit = TRUE)
Stack trace (innermost first):
51: observeEvent
50: module
49: withReactiveDomain
48: callModule
47: 
46: do.call
45: server
3: shiny::runApp
2: runGadget
1: esquisse::esquisser
Error in observeEvent(input$changeData, { :
unused argument (ignoreInit = TRUE)
#####################################################

The window opens and crashes with this error message, Please suggest how to resolve this issue?
My R Studio version is 1.0.153

**Comment by pvictor** [comment]
Hi!
Thanks for the report, which version of `shiny` do you use ? `esquisse` require at least 1.0.0.
I'll update the description with this info.

Victor

**Comment by nitin194** [comment]
Thanks for the reply @pvictor 

I installed the pre-compiled binary of latest shiny which resolved the issue.

**Comment by pvictor** [comment]
Perfect!

**Comment by sourabhXIII** [comment]
Hi @nitin194 
Can you please guide me with "pre-compiled binary of latest shiny"?
How can I install it?

**Comment by sourabhXIII** [comment]
> Hi @nitin194
> Can you please guide me with "pre-compiled binary of latest shiny"?
> How can I install it?

Do not worry. I figured it out. `devtools::install_github("rstudio/shiny")`
