### ISSUE TITLE
error using sf data in combination with size

### ISSUE THREAD

**Issue by itcarroll** [dreamRs/esquisse#29]
Worked awesome with the meuse dataset's landuse variable set to "Color", but borked on setting the same to "Size".

```
data('meuse', package = "sp")
df <- sf::st_as_sf(meuse, coords = c('x', 'y'), crs = 28992)
esquisser(df)
```

<img width="854" alt="screen shot 2018-10-09 at 10 48 53 pm" src="https://user-images.githubusercontent.com/3383837/46710396-9b7f7080-cc15-11e8-8fe7-aa1ec380bc4d.png">

esquisser version: 9340e358af76f6f44307d4501ce2659fd34eec6f

**Comment by pvictor** [comment]
Hi!
Probably in issue in `ggplot2`, `size` dont seems to handle missing values, if you remove it, it works : 

```r
library(ggplot2)
data('meuse', package = "sp")
df <- sf::st_as_sf(meuse, coords = c('x', 'y'), crs = 28992)
# one missing value : error
ggplot(data = df) +
  aes(size = landuse) +
  geom_sf() +
  theme_minimal()

# remove missing value : works
df <- df[!is.na(df$landuse), ]
ggplot(data = df) +
  aes(size = landuse) +
  geom_sf() +
  theme_minimal()
```

I took the opportunity to add a better management of warnings and errors, now it looks like this: 

![image](https://user-images.githubusercontent.com/4415580/46733622-1e91dc80-cc91-11e8-8cac-ae177f4eb4a9.png)

**Comment by itcarroll** [comment]
Nice! Maybe I'll poke the tidyverse ...
