### ISSUE TITLE
License Info

### ISSUE THREAD

**Issue by zblumen** [dreamRs/esquisse#31]
@pvictor  Excellent work! Is it possible to provide more clarity/detail around your LICENSE?  Do you intend for this not to be open source?  Thank you!

**Comment by pvictor** [comment]
I've updated the LICENSE file (but the package has always been under GPLv3) : 

> The esquisse package as a whole is distributed under GPL-3 (GNU GENERAL PUBLIC
LICENSE version 3).

**Comment by zblumen** [comment]
thank you for clarifying! Closing this issue
