### ISSUE TITLE
Add grouping variable

### ISSUE THREAD

**Issue by guiastrennec** [dreamRs/esquisse#32]
First of all great package ! I would however like to suggest the followings: 
1) the addition of a `group` variable in the main mapping panel.
2) the addition of a `position` argument (e.g. stack, dodge, fill) under the "plot options" tab when a group variable has been defined.

**Comment by TheNetAdmin** [comment]
Need the grouping as well, grouping will make esquisse a masterpiece.

**Comment by pvictor** [comment]
Hello!
I added a box for choosing "group" aesthetic (I think that's the last one regarding horizontal space).
Re-install from GitHub and try: 

```r
esquisser(nlme::Oxboys)

# and plot lines with group = Subject 
ggplot(data = nlme::Oxboys) +
  aes(x = age, y = height, group = Subject) +
  geom_line(color = "#0c4c8a") +
  theme_minimal()
```

Victor

**Comment by guiastrennec** [comment]
I just tested it it works great, thank you for considering my suggestion. I look forward to the position argument now 😄

**Comment by TheNetAdmin** [comment]
Great job!

**Comment by guiastrennec** [comment]
@pvictor I typically use group on line plots e.g.

```r
ggplot(data = Theoph, aes(x = Time, y = conc, group = Subject)) + 
  geom_line()
```
![rplot05](https://user-images.githubusercontent.com/7304883/48807363-9e45a900-ed1d-11e8-87ab-7ad31604d900.png)

**Comment by pvictor** [comment]
Ok I added `geom_area` as well and you can now use `position` argument for lines & area!
