### ISSUE TITLE
Power point keeps opening up

### ISSUE THREAD

**Issue by guiastrennec** [dreamRs/esquisse#33]
I really like the power point functionality but there seems to be a bug, once I clicked on the Power point button if any modifications are made to the graph after that it causes the app to refresh and re-export the graph to power point again and again. The same behavior happens if I try to click the PNG button after the Power Point it keeps exporting to pptx.

It would be nice to ensure that the graph is only exported when the power point button is clicked.

**Comment by pvictor** [comment]
You're right, it's not the expected behavior. It's fixed.
Thanks for reporting the issue !

Victor
