### ISSUE TITLE
builder not showing any graphs

### ISSUE THREAD

**Issue by kenujen** [dreamRs/esquisse#37]
I was wondering if anyone has the same problem... my builder does almost everything find except for showing the preview of the graphs. Any idea how to go get the graphs to show up? 

Win10, R3.5.1

Thanks.

**Comment by pvictor** [comment]
Hello,
Can you provide a screenshot of what's happenning ? Not sure to fully understand the problem.
And can you send the result of this line : 

```r
devtools::session_info()
```

Victor

**Comment by pvictor** [comment]
I had a similar issue after updating Shiny to 1.2.0, try re-install from GitHub and tell me if it was that : 

```r
devtools::install_github("dreamRs/esquisse")
```

**Comment by kenujen** [comment]
> I had a similar issue after updating Shiny to 1.2.0, try re-install from GitHub and tell me if it was that :
> 
> ```r
> devtools::install_github("dreamRs/esquisse")
> ```

Hi Victor,
Actually I did the re-installation right after I ran into the problem and it works fine now. Thanks!
-Ken.
