### ISSUE TITLE
Smooth lines not added in the code window

### ISSUE THREAD

**Issue by donsvensen** [dreamRs/esquisse#4]
Hi 

I am testing your tool via PowerBI actually and when I use the designer to add smoothed lines in a scatter chart - it works fine in the designer but the code doesn't get updated with the 

Before

ggplot(data = dataset) +
  aes(x = Sales_Amount, y = Sales_Profit, color = BusinessType) +
  geom_point() +
  theme_minimal()

and after

ggplot(data = dataset) +
  aes(x = Sales_Amount, y = Sales_Profit, color = BusinessType) +
  geom_point() +
  theme_minimal()

Hope you can solve this

Best regards
Erik

**Comment by pvictor** [comment]
Oups I forgot to generate the code...
I'll look into it!

Victor

**Comment by pvictor** [comment]
It should work!

Victor
