### ISSUE TITLE
Adding plotly option

### ISSUE THREAD

**Issue by ucoque** [dreamRs/esquisse#40]
Hi,

First of all thank for this esquisse tool, i found it really interesting.

Have you think about adding plotly option so plots can be dynamic?

regards #

**Comment by pvictor** [comment]
Hi,
Thank you ! Support for plotly is planned for a later version, see #34.

Victor

**Comment by ucoque** [comment]
Oh, great, and sorry. 

thanks

**Comment by pvictor** [comment]
No worries, it's a feature more and more requested 😄
