### ISSUE TITLE
[Feature Request] scatterplot point shape

### ISSUE THREAD

**Issue by Pascoe70** [dreamRs/esquisse#45]
A way to change the point shape - possibly using 'schemes' in a similar fashion to the colour scheme templates, either explicitly stating the 0-25 geom_point value in one column of the data frame or by using factors, would be really useful

**Comment by p-schaefer** [comment]
This would be great!

**Comment by pvictor** [comment]
It is now available in the GitHub version and will be released on CRAN soon, please re-open this issue if you encounter any trouble.
