### ISSUE TITLE
[Feature Request] Y axis on facet wrap scatterplots - individual scaling

### ISSUE THREAD

**Issue by Pascoe70** [dreamRs/esquisse#47]
The ability to have either individual or harmonised Y axis ranges on facet_wrapped scatterplots would be extremely useful. Often the fact that the ranging forces to a value that accommodates all facets renders some of the individual facet plots less usable.

**Comment by pvictor** [comment]
This is now possible to set `scales` argument from `facet_wrap`.
Please install dev version to test it.

Victor

**Comment by Pascoe70** [comment]
Hi Victor

I have never installed dev version before and have no idea how to do it - do I need the master version or something like that? As it looks like the link to dev version here in the repo is for before the commit that you're describing. I am probably doing something really dumb. Sorry. And thanks for the great work.

**Comment by pvictor** [comment]
Hello,
No worries, first time for everything. The lastest version is on the master branch, so you can get it with : 

```r
remotes::install_github("dreamRs/esquisse")
```

**Comment by Pascoe70** [comment]
Seems not to be working. Suspect I have to uninstall the CRAN package first as in 'version' it says 0.1.7... I'll give that a try.

**Comment by pvictor** [comment]
No need to uninstall, maybe try to close all your RStudio sessions and try in a fresh one. If you continue to have problems, you can send the error message and the result of `sessionInfo()`.

**Comment by Pascoe70** [comment]
There isn't an error message per se. I just can't get it to use the dev version of the package. I uninstalled the cran version then installed the dev version (had to donload as a zipped file and then manually point to it in RStudio using the install button) and I just can't get away from that prod 0.1.7 version.

Presumably one way I'll know instantly if I get it to work is that when I call it, there will be a Group option somewhere on the top line (currently I only have X, Y, Fill, Color, Size, Facet)

**Comment by pvictor** [comment]
You don't have access to intenrent on your computer ? Running `remotes::install_github("dreamRs/esquisse")` in your console, you'll get the last version.
I plan to release on CRAN by the end of the week, it will be easier.

**Comment by Pascoe70** [comment]
Ahhhh ok - I think I will wait for the CRAN release then. I do have internet access but I suspect this is something to do with corporate firewall.

Thanks so much again for your help and your great work on this...

**Comment by Pascoe70** [comment]
Outstanding. 'Free Y' option was just what I needed but you have overdelivered again ;-)

Now I just need to go research what the X and Y axis transforms are. Good work yet again...

**Comment by Pascoe70** [comment]
Ok so something a little wierd is now happening since I updated the package. I am working with a quite modest dataset (686 rows, 60 columns) and I can only plot a subset of the data. What isn't clear to me is how or why this particular subset is all that's visible.

It's not a dataset I would be allowed to share so hard to give concrete examples. I will try and replicate with a known canned dataset from elsewhere and share what I find.

It's possible it may be something quite simple (eg I only recently discovered that there seems to be a limit of 49 unique values (whether factored or not) for a column, above which that column won't even appear in the 'Data' filtering section as a column that can be manipulated. So maybe some aspect of the precise dataset I am using is causing a problem...

**Comment by Pascoe70** [comment]
Looks like column numbers as I pruned quite a large number of columns and now it's ok again. I just don't quite know precisely what the restriction is.....

**Comment by pvictor** [comment]
Glad you'll be able to install the new version !
Mmmh I made a lot of internal changes, so it's possible there's some bugs to resolve. If you manage to reproduce your problem I'm very interested !

**Comment by Pascoe70** [comment]
Appears to be an issue if too many columns. I reduced width of the dataset
in question from 60 to 37 and it worked. On Monday I'll try and see if I
can isolate a firm restriction as that number 37 was arbitrary and only
based on which columns I knew had no interest to me in the dataset. The
real cutoff is likely somewhere between there and 60. Only 800 rows so
unlikely it was the size of the data frame.
