### ISSUE TITLE
Error in loading RStudio  viridislite 

### ISSUE THREAD

**Issue by davidfombella** [dreamRs/esquisse#48]
Error in getExportedValue(pkg, name) : 
  cannot open file '~/R/win-library/3.5/viridisLite/data/Rdata.rdb': No such file or directory
In addition: Warning message:
In getExportedValue(pkg, name) : restarting interrupted promise evaluation

**Comment by pvictor** [comment]
Does the problem persist?
The only solution I know for this kind of issues is to restart R and re-install packages...

Victor

**Comment by SocProf** [comment]
My solution to this was to re-install R in the C directory.
