### ISSUE TITLE
Crash when deselecting all categorical variables

### ISSUE THREAD

**Issue by aleruete** [dreamRs/esquisse#50]
Hi! great package! Thank you
I just observed that when deselecting all categories of a categorical variable in the "Data" filters, the app/window crashes (even in "pause" mode). It seems obvious that at least one category should be included, but may be some message to prevent this happening or somehow disabling the selector if only one remaining, would be a good solution. 

Cheers

Alejandro

**Comment by pvictor** [comment]
Thanks for reporting this! Sjould work fine now!

Best, Victor

**Comment by aleruete** [comment]
Thank you! shall I update from Github?

**Comment by aleruete** [comment]
Like a charm! thank you!!!
