### ISSUE TITLE
[Feature Request] Option to set port for browser display

### ISSUE THREAD

**Issue by DanielLearner** [dreamRs/esquisse#51]
Right now a random port is assigned by r shiny.  It would be useful to be able to make this port a constant value.

**Comment by pvictor** [comment]
Hi Daniel,

That's actually a `shiny` option, you can choose port like this:

```
library(esquisse)
options("shiny.port" = 8080)
esquisser(iris, viewer = "browser")
```

However, I can add an argument to the `esquisse` function to choose the port if the method above does not suit your need.

Victor
