### ISSUE TITLE
Esquisse crashing

### ISSUE THREAD

**Issue by SocProf** [dreamRs/esquisse#52]
When running esquisse:: esquisser(data) in R Studio, the esquisse window opens and crashes with the error message:
Loading required package: shiny

Listening on http://127.0.0.1:4000
Warning: Error in badgeType: length(col_name) == length(col_type) is not TRUE
  80: <Anonymous>

I have shiny 1.2.0 installed and loaded.

**Comment by pvictor** [comment]
Hello,
What is `data` ? Can you send output of `str(data)` please ?

Victor

**Comment by SocProf** [comment]
It's the starwars dataset in dplyr.

**Comment by pvictor** [comment]
Thanks, it was because of list columns, they are now dropped (don't sure there's a way to visualize them with `ggplot2`).

Victor
