### ISSUE TITLE
bookmarking

### ISSUE THREAD

**Issue by itcarroll** [dreamRs/esquisse#54]
Shiny's [bookmarking](https://shiny.rstudio.com/reference/shiny/0.14/enableBookmarking.html) feature is really great! You can save the state of your app to file or to a URL query string, and restore in a new Shiny session ... if your inputs and outputs can do it.

I wanted bookmarking to work with esquisse, and I think I mostly dit it. Are you interested in a PR?

[Here](https://github.com/SESYNC-ci/esquisse/tree/thetis) is the feature branch.

[Here](https://gitlab.sesync.org/snippets/29) is a demo app.R.

**Comment by pvictor** [comment]
Hi Ian,

This seeems very nice! Yes you can send a PR!
Thanks!

Victor

**Comment by itcarroll** [comment]
See #55.
