### ISSUE TITLE
Run with host option

### ISSUE THREAD

**Issue by xiaodaigh** [dreamRs/esquisse#56]
With Shiny I can `runApp(host= "10.10.10.10")` where host is my computer's IP address then all computers on the network can access my app. With `esquisser` it's not possible to choose the host. And I see that it's running `shiny::runGadget`. 

But it would be awesome to be able to self-host some slice and dice on data that's only on my computer.

**Comment by pvictor** [comment]
Hi, you can change host with shiny's option `"shiny.host"`, e.g. :  

```r
options("shiny.host", "10.10.10.10")
esquisse::esquisser()
```
Is that what you're looking for ?

Otherwise, there's also the possibility to use esquisse modules to include theme in your own application and use `runApp` as you want (see `?esquisse::esquisserUI`)

Victor
