### ISSUE TITLE
Facets?

### ISSUE THREAD

**Issue by DataStrategist** [dreamRs/esquisse#6]
This package is awesome and I love the simplicity with which we can quickly get to something viewable. Still.. are you planning to add facets as  abox? I rarely work without them.

Thanks!

**Comment by pvictor** [comment]
Thank you! 
It's definitely possible! I let you know!

Victor

**Comment by pvictor** [comment]
Hi @itcarroll !
Thanks for looking into this feature !
You want to add a supplementary box in the drag and drop module ? If you set `replace = FALSE` this will affect all the other boxes and breaks some things... So i can imagine two solutions : 

* add two new boxes in the drag and drop module (don't know if there is enough space)
* add two classics selects menu in the "plot options" menu.

What do you think ? Have you another idea ?

If you have screenshots with your updates it'll be cool :)

Victor

**Comment by DataStrategist** [comment]
My 2 cents... perhaps start w/ the simple selects to ensure functionality... and when we're sure there's no bugs, perhaps it could potentially become new boxes? Just to keep the awesome aesthetic? 
</2 cents>

Thanks for working on this you twooooo

**Comment by itcarroll** [comment]
What I have so far just adds a "facet" box to the drag and drop.
![screen shot 2018-10-09 at 9 41 52 am](https://user-images.githubusercontent.com/3383837/46673463-cdf28480-cba7-11e8-82f0-7039dea25d99.png)

It doesn't look too crowded (although the right-alignment is a bug), but a row-facet and col-facet does start to go overboard. I was suggesting that the `replace` argument could be extended in a way to let different boxes have different replace `settings`, which would allow row and col faceting and possibly other new features ... like multiple y-axis variables.

**Comment by pvictor** [comment]
Awesome! 
It's actually much cooler to use the drag and drop module :D
Don't worry the right-alignment has never been perfect (margins issue), i'll look into it.
That's may be possible, but it's JavaScript :) 
I'm going to give it a try.

Victor

**Comment by DataStrategist** [comment]
Wow that looks great. Nice job Carol! I think that's a probably enough no?
Drag and drop ggplot with getting capabilities is not nothing!

**Comment by itcarroll** [comment]
Thanks, @pvictor for the merge, the acknowledgment, and for completing the job within the code-module (totally forgot about that part!). Looks like this issue is  🚫!

**Comment by DataStrategist** [comment]
I'll let @pvictor do the honors of closing... not sure if there was anything else needed here. Thanks all!

**Comment by pvictor** [comment]
Thank you all!

**Comment by pvictor** [comment]
On CRAN 🎉

**Comment by DataStrategist** [comment]
Good job!!!! Congratulations! Your first?
