### ISSUE TITLE
issues on installing "gdtools" and "esquisse" and "Cairo" Reason"image not found"

### ISSUE THREAD

**Issue by wellthank** [dreamRs/esquisse#67]
First, i installed with

> install.packages("esquisse", dependencies = c("Imports", "Suggests"))

URL’https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/esquisse_0.2.1.tgz'
Content type 'application/x-gzip' length 1304502 bytes (1.2 MB)
==================================================
downloaded 1.2 MB

then, errors:

>esquisse:::esquisser()`

Error in dyn.load(file, DLLpath = DLLpath, ...) : 
unable to load shared object ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/gdtools/libs/gdtools.so’：:
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/gdtools/libs/gdtools.so, 6): Library not loaded: /opt/X11/lib/libcairo.2.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/gdtools/libs/gdtools.so
  Reason: image not found

i also tried "gdtools" and "Cairo", same errors:

>  library("Cairo")
Error: package or namespace load failed for 'Cairo':
 .onLoad failed in loadNamespace() for 'Cairo', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Cairo/libs/Cairo.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Cairo/libs/Cairo.so, 6): Library not loaded: /opt/X11/lib/libfreetype.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/Cairo/libs/Cairo.so
  Reason: image not found

> library("gdtools")
Error: package or namespace load failed for 'gdtools' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/gdtools/libs/gdtools.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/gdtools/libs/gdtools.so, 6): Library not loaded: /opt/X11/lib/libcairo.2.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/gdtools/libs/gdtools.so
  Reason: image not found

I'm running MacOS v10.14.6,R studio v 1.2.1335,R v3.6.1
Thanks

**Comment by pvictor** [comment]
Hello,
Try yo re-install {gdtools} from a fresh  R session, see if you can load it.
Otherwise maybe an issue with cairo, this issue might help : https://github.com/dreamRs/esquisse/issues/7

Victor

**Comment by robertwwalker** [comment]
I believe your issue is the same as #74.

I am not a Mac user, but I have seen this issue.

gdtools and Cairo both have system level dependencies on a Mac that are not in default installations.  The following three step process seems to solve it.

First install homebrew.
Second, brew install cairo
Third, brew install freetype

Then you will need to reinstall the R packages that depend on them and throw errors above.

**Comment by wellthank** [comment]
Thank you very much!
I have solved the problem following your tutorial.


| |
njmuhxx
|
|
njmuhxx@163.com
|
签名由网易邮箱大师定制


在2019年10月10日 03:05，Robert W. Walker<notifications@github.com> 写道：

I believe your issue is the same as #74.

I am not a Mac user, but I have seen this issue.

gdtools and Cairo both have system level dependencies on a Mac that are not in default installations. The following three step process seems to solve it.

First install homebrew.
Second, brew install cairo
Third, brew install freetype

Then you will need to reinstall the R packages that depend on them and throw errors above.
