### ISSUE TITLE
Change the location where the code is inserted in shiny script.

### ISSUE THREAD

**Issue by IamVDB** [dreamRs/esquisse#68]
Hello guys. 
I love this esquisse package and I have integrated it in a shiny dashboard where I upload data about company’s financial history. I am using the shinydashboard package to structure my shiny application. I would love to be able to insert the plots I make into a separate Tabitem. I was wondering if anybody knows how to change the inserted plot code to a specific location in your script.

**Comment by pvictor** [comment]
Hello,
The "Insert code in script" only works in RStudio. In a shiny app, you can retrieve the code as the return value of the module. But only code for last plot created is available, we are considering adding a "history" feature, but for now you have to do it by yourself. Let me know if i'm unclear, i'll post an example.

Victor

**Comment by IamVDB** [comment]
Thank you for your quick response! 
Do you maybe have any suggestions or examples on how I could change the current “insert code in script” to go directly to a tabitem where it will be displayed. This way I create my own “history” feature of plots that I need to argument the points I want to make.

**Comment by pvictor** [comment]
Hello, you can try th foolowing code, careful I used the last version of esquisse from Github : 

```r
library(shiny)
library(shinydashboard)
library(esquisse)

sidebar <- dashboardSidebar(
  sidebarMenu(
    id = "tabs",
    menuItem("esquisse", tabName = "esquisse", icon = icon("wrench")),
    menuItem("code", icon = icon("code"), tabName = "code")
  )
)


body <- dashboardBody(
  tabItems(
    tabItem(
      tabName = "esquisse",
      box(
        title = "esquisse",
        width  = NULL,
        esquisserUI(
          id = "esquisse",
          header = FALSE
        ),
        br(),
        actionButton("save", "Save plot"),
        actionButton("go", "Go next tab")
      )
    ),
    tabItem(
      tabName = "code",
      verbatimTextOutput("saved_code")
    )
  )
)

shinyApp(
  ui = dashboardPage(
    dashboardHeader(),
    sidebar,
    body,
    title = "Dashboard example"
  ),
  server = function(input, output, session) {
    
    result <- callModule(
      module = esquisserServer,
      id = "esquisse",
      data = reactiveValues(data = iris, name = "iris")
    )
    
    saved_plots <- reactiveValues(code = NULL)
    
    observeEvent(input$save, {
      saved_plots$code <- c(saved_plots$code, result$code_plot)
    })
    
    observeEvent(input$go, {
      updateTabItems(session, "tabs", "code")
    })
    
    output$saved_code <- renderPrint({
      cat(saved_plots$code, sep = "\n")
    })
    
  }
)
```

**Comment by IamVDB** [comment]
wow that is awesome men!!!
i was just wondering if it is als possible to show the image instead of only the code of the plot?
