### ISSUE TITLE
The viewer stays blank, no graphs appear

### ISSUE THREAD

**Issue by YeWnos** [dreamRs/esquisse#69]
Hello everyone, 

I have successfully installed esquisse and have already tried to answer my problem by launching esquisse in the browser and in Rstudio but it does not change anything. In both case, I have absolutely no preview of the graph I am trying to get (screenshot attached). My data does not contain any missing values and so far I have tried to relaunch R and reinstall esquisse several repeatedly. Also, I paused/relaunched the viewer several times and it does not work either. 
Finally, I have tried to copy the code from esquisse and run it with Rstudio and it works, ggplot2 produces my plot. 
I am a begineer in this field so any help would be appreciated ! 

![image](https://user-images.githubusercontent.com/54531065/63679344-678f4880-c7f1-11e9-959e-57c8dc39bd9b.png)

**Comment by pvictor** [comment]
Hi,
If you have enable the "pause" mode, this block the graphic to be generated, you have to click on it to activate update.

Victor

**Comment by YeWnos** [comment]
Hi,
I already tried several times to enable/disable the pause mode but it's not working. :(

![image](https://user-images.githubusercontent.com/54531065/63681222-a32c1180-c7f5-11e9-9cc6-53bc01857ed8.png)

**Comment by pvictor** [comment]
Arf that's weird...

Can you share your data ? You can send them by mail if you want (victor.perrier@dreamRs.fr)

Victor

**Comment by YeWnos** [comment]
Hi, 

Thank you very much, your answer gave me an idea, I was so convinced that it came from the package that I did not consider at all that it could be an error caused by the data file. I tried to load another data file and it worked fine ! I don't understand why but it works ! 
Sorry for the inconvenience, this package is amazing !

**Comment by pvictor** [comment]
Glad you solved the problem and thank you for the compliment!

**Comment by jgires** [comment]
Hello,

Very great library, thanks for your work !

I have exacly the same problem with a database of 4200 obs. & 260 variables : the viewer stays blank.

It works if I select only columns I need, but it's not practical. It's maybe related to the database structure ?

Joël
