### ISSUE TITLE
Can't install because of issue installing 'gdtools'

### ISSUE THREAD

**Issue by jrpeck1989** [dreamRs/esquisse#7]
I run `install.packages("gdtools", type = "source")` I get the following error message (both in RStudio and in Terminal:

> install.packages("gdtools", type = "source")
trying URL 'https://cran.ma.imperial.ac.uk/src/contrib/gdtools_0.1.7.tar.gz'
Content type 'application/x-gzip' length 35268 bytes (34 KB)
==================================================
downloaded 34 KB

* installing *source* package ‘gdtools’ ...
** package ‘gdtools’ successfully unpacked and MD5 sums checked
Using PKG_CFLAGS=-I/usr/local/opt/cairo/include/cairo
Using PKG_LIBS=-L/usr/local/opt/cairo/lib -lcairo
** libs
clang++  -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/usr/local/opt/cairo/include/cairo -I../inst/include/ -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include" -I/usr/local/include   -fPIC  -Wall -g -O2  -c CairoContext.cpp -o CairoContext.o
In file included from CairoContext.cpp:7:
/usr/local/opt/cairo/include/cairo/cairo-ft.h:46:10: fatal error: 'ft2build.h' file not found
#include <ft2build.h>
         ^~~~~~~~~~~~
1 error generated.
make: *** [CairoContext.o] Error 1
ERROR: compilation failed for package ‘gdtools’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/gdtools’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/gdtools’
Warning in install.packages :
  installation of package ‘gdtools’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/y8/6klg_4dx4gjgvhv5q6tf9qj00000gn/T/RtmpJ2Yvb6/downloaded_packages’

I've tried updating, upgrading and reinstalling cairo through Homebrew multiple times to no effect. 

I'm running MacOS v10.13.4, RStudio v1.1.453, R v3.5.0

**Comment by jcmaerz3** [comment]
Having the same issue running on same OS, RStudio, and R versions.

**Comment by adamBirenbaum** [comment]
I also tried updating, upgrading and reinstalling cairo which did not help.

The solution which worked for me was:
` brew install pkg-config`
`install.packages("gdtools", type = "source")`
`devtools::install_github("dreamRs/esquisse")`

**Comment by vsteiger** [comment]
hi @jrpeck1989, this worked for me:

Install [https://www.xquartz.org](url)
log out/in
```
brew install cairo (you might use sudo)
source("https://install-github.me/dreamRs/esquisse")

```

**Comment by jcmaerz3** [comment]
Regrettably, neither of those fixes worked for me. The list of error messages is too long to imaging. The first error message seems most important:

> install.packages("gdtools", type = "source")
trying URL 'https://cran.rstudio.com/src/contrib/gdtools_0.1.7.tar.gz'
Content type 'application/x-gzip' length 35268 bytes (34 KB)
==================================================
downloaded 34 KB

* installing *source* package ‘gdtools’ ...
** package ‘gdtools’ successfully unpacked and MD5 sums checked
Auto-brewing cairo in /var/folders/ks/vvf6cg0j37795rsnkvy97y5m0000gn/T//build-cairo...
Error: Git must be installed and in your PATH!
Error: Git is unavailable

**Comment by vsteiger** [comment]
what does it say, when you enter in osx terminal:

`git help -a`

**Comment by jcmaerz3** [comment]
git help -a

xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

**Comment by jcmaerz3** [comment]
I don't know whether I am making progress, but I tried a clean install and installing on a separate computer also running R 3.5.0 on OSX 10.13.4 and R studio 1.1.447. I got far fewer error messages than before, but appear stuck here. The issue still appears to be a file path issue with gdtools.

 > source("https://install-github.me/dreamRs/esquisse")
Downloading GitHub repo dreamRs/esquisse@master
Downloading GitHub repo dreamRs/shinyWidgets@master
* installing *source* package ‘shinyWidgets’ ...
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (shinyWidgets)
Skipping 1 packages ahead of CRAN: shinyWidgets
* installing *source* package ‘esquisse’ ...
** R
** inst
** byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/gdtools/libs/gdtools.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.5/Resources/library/gdtools/libs/gdtools.so, 6): Library not loaded: /opt/X11/lib/libcairo.2.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.5/Resources/library/gdtools/libs/gdtools.so
  Reason: image not found
ERROR: lazy loading failed for package ‘esquisse’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/esquisse’
Warning message:
In utils::install.packages(...) :
  installation of package ‘/var/folders/ks/vvf6cg0j37795rsnkvy97y5m0000gn/T//Rtmp8xJ7iK/remotes3e9112047f26/dreamRs-esquisse-170fc93’ had non-zero exit status

**Comment by davidgohel** [comment]
Have a look here : https://github.com/davidgohel/gdtools/issues/43#issuecomment-375056815

Also, don't forget to pen xcode software and be sure you accepted the licence agreement (which could block compilation!).

**Comment by vsteiger** [comment]
@jcmaerz3 I had the exact same error: re-install Quartz aka X11 for Mac...restart...then progress..this worked out for me

**Comment by sfd99** [comment]
Having _exactly the same installation problem_
(as described above),
in: **UBUNTU LINUX 14.04 LTS - 32bits
with latest R and Rstudio.**
Any solution?
(looking forward to trying Esquisse out...).

**Comment by thechez** [comment]
I managed to get it working with a reboot followed by installing cairo via brew. Then just installed gdtools as well as esquisse in R. Looking forward to seeing how this works!

**Comment by slyrus** [comment]
For what it's worth, I'm seeing this problem again.

From the command line, pkg-config seems to be doing the right thing:

```
(sly@montalcino):~$ pkg-config cairo --cflags
-I/usr/local/Cellar/cairo/1.14.12/include/cairo -I/usr/local/Cellar/glib/2.58.0_1/include/glib-2.0 -I/usr/local/Cellar/glib/2.58.0_1/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.42/include -I/usr/local/Cellar/fontconfig/2.13.1/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/libpng/1.6.35/include/libpng16 -I/opt/X11/include/pixman-1
(sly@montalcino):~$ pkg-config cairo --libs
-L/usr/local/Cellar/cairo/1.14.12/lib -lcairo
```

Yet when I try from R, I get:

```
Installing gdtools
'/usr/local/Cellar/r/3.5.1/lib/R/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/lm/gh83qhvd14d9nwkl58zwbrsw0000gn/T/RtmpGyho3e/devtools26664f28808/gdtools'  \
  --library='/usr/local/Cellar/r/3.5.1/lib/R/library' --install-tests 

* installing *source* package ‘gdtools’ ...
** package ‘gdtools’ successfully unpacked and MD5 sums checked
Found pkg-config cflags and libs!
Using PKG_CFLAGS=
Using PKG_LIBS=-L/usr/local/Cellar/cairo/1.14.12/lib -lcairo
```
so the PKG_LIBS args are right, but the PKG_CFLAGS are hosed.

**Comment by slyrus** [comment]
If I run install.packages("gdtools") from and R process started from a Terminal.app shell, things work OK. If I try that from and R process started via ESS, it fails as above.

**Comment by pvictor** [comment]
Hello,
{esquisse} is now on CRAN and binaries have been build, you can install with : 

```r
install.packages("esquisse")

# with all dependencies
install.packages("esquisse", dependencies = c("Imports", "Suggests"))
```

If you have new installation problems with this command, please open a new issue.

Victor

**Comment by karthikkommalapati** [comment]
Hello,

I have tried all the steps above, but I am still having this error.

Any other suggestions? 


Kind Regards,
Karthik 

![image](https://user-images.githubusercontent.com/43684109/67241086-adac0580-f44a-11e9-9818-a100f737b99d.png)

**Comment by karthikkommalapati** [comment]
The issue now resolved. followed instructions from here and it is working now.

https://community.rstudio.com/t/unable-to-load-packages-libcairo-2-dylib-not-loaded/22754


Kind Regards,
Karthik
