### ISSUE TITLE
Suggestion: Data manipulation

### ISSUE THREAD

**Issue by daricomp** [dreamRs/esquisse#79]
The actual implementation saves in the same objet the data manipulation realized with dplyr, while it would be better not to. 
It also creates two code blocks, when it would be better to have only one. 
Example follows.

Actual: 

diamonds <- diamonds %>%
filter(carat < 4)

ggplot(diamonds) +
aes(x = carat) +
geom_histogram()

Suggestion:

diamonds %>%
filter (carat < 4) %>%
ggplot () +
aes(x = carat) +
geom_histogram()

**Comment by GegznaV** [comment]
I agree that a plotting tool should not modify original data and `%>%` syntax would be a better choice.

**Comment by pvictor** [comment]
Makes sense, implemented in `0.2.3`.

Thanks,

Victor
