### ISSUE TITLE
Typo in the ui: 'choosed' should be 'chosen'

### ISSUE THREAD

**Issue by tomsing1** [dreamRs/esquisse#8]
`choosed` should be `chosen`:

https://github.com/dreamRs/esquisse/blob/1ae3d4ba285368c467c73937901c4ff13a94e36b/R/module-chooseData.R#L150

https://github.com/dreamRs/esquisse/blob/1ae3d4ba285368c467c73937901c4ff13a94e36b/R/module-chooseData.R#L299

`choosed` should be `chose`:

https://github.com/dreamRs/esquisse/blob/ef45c86f09247523ef1ac4ee49915649894ad6fc/R/ggplot_to_ppt.R#L87

**Comment by pvictor** [comment]
Thank you! It's corrected.

Victor
