### ISSUE TITLE
 Add a vertical slider for "Plot options"

### ISSUE THREAD

**Issue by GegznaV** [dreamRs/esquisse#80]
If Esquisse window is big (i.e., screen resolution is high enough and magnification in RStudio is low enough), no problems exist:
![image](https://user-images.githubusercontent.com/12725868/67669992-a3729580-f97b-11e9-8aa3-3787643092f9.png)

But if the window is small, some contents are not visible and scrolling with the mouse does not help:
![image](https://user-images.githubusercontent.com/12725868/67670016-ad949400-f97b-11e9-9e25-cf01578a9036.png)

In some situations, a vertical slider for "Plot options" (as well as for the other windows) would be helpful. This feature exists in "Data" window:

![image](https://user-images.githubusercontent.com/12725868/67670338-5ba03e00-f97c-11e9-83b9-f20963940f57.png)

**Comment by pvictor** [comment]
Thanks for reporting this, and the detailled issue. That's fixed in `0.2.3`.

Victor
