### ISSUE TITLE
Filtering data adds empty rows for data sets that contain NAs

### ISSUE THREAD

**Issue by Beast199** [dreamRs/esquisse#82]
![Capture](https://user-images.githubusercontent.com/57100141/67683378-f5c2af00-f999-11e9-8087-68a26efec239.JPG)
Running the example shiny app,it shows 27 entries with years from 2003 to 2004, but they are all completely empty rows. Is this a bug?

**Comment by pvictor** [comment]
Can you provide results of `sessioninfo::package_info("esquisse", include_base = FALSE, dependencies = FALSE)` ?
I made a lot of changes in this module last week to work with `NA`, maybe you haven't the last commit.
I don't have the same result.

Victor

**Comment by Beast199** [comment]
It seems that I had the version 0.2.2 installed from CRAN
 package  * version date       lib source        
 esquisse * 0.2.2   2019-08-22 [1] CRAN (R 3.5.3)

Installing the latest version from GitHub solved it. 
Thank you!
