### ISSUE TITLE
Axis-transform

### ISSUE THREAD

**Issue by wilfriedmonangeIRSN** [dreamRs/esquisse#83]
Hi, with release 0.2.2 of esquisse I get the following error while selecting any transformation apart from identity (log10, log2, etc.):
Error : could not find function "scale_x_continuous"

![Screenshot from 2019-11-05 09-26-38](https://user-images.githubusercontent.com/45367868/68190845-83ac2480-ffae-11e9-9bcd-84ff3b41c754.png)

**Comment by pvictor** [comment]
Thanks for reporting this, there was a missing import.
this should work, note however that some transformations require a parameter that is not currently possible to specify (todo in a future release).

Victor
