### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by lgellis** [dreamRs/esquisse#9]
**Issue on initial install using:** 

- install_github("dreamRs/esquisse")
OR
- devtools::install_github("dreamRs/esquisse")

**Error is:** 

ERROR: dependency ‘officer’ is not available for package ‘esquisse’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/esquisse’
Installation failed: Command failed (1)

**I then installed the officer package**

install.packages("officer")
library(officer)

**However the package still could not be installed**

** preparing package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/gdtools/libs/gdtools.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/gdtools/libs/gdtools.so, 6): Library not loaded: /opt/X11/lib/libcairo.2.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/gdtools/libs/gdtools.so
  Reason: image not found
ERROR: lazy loading failed for package ‘esquisse’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/esquisse’
Installation failed: Command failed (1)

**Comment by sfd99** [comment]
Unfortunately,
lots of installation problems
in both MAC and in Linux
with this pkg...
(see other Issues thread in GIT).

Wish the author would address them here.
Anybody seen any author responses
to these installation problems?.

I just can't install it 
in Ubuntu Linux 14.04 32-bit LTS,
with latest versions of R and Rstudio... :-(

**Comment by pvictor** [comment]
You have to install packages `rvg` and `gdtools`, your issue is with `gdtools`, try installing from CRAN : 

```r
install.packages("gdtools")
```

Then run : 

```r
source("https://install-github.me/dreamRs/esquisse")
```

If it doesn't work, try installing Cairo manually: 

```
brew update
brew upgrade
brew reinstall cairo
```

**Note:** you have to run commands above with all your R session closed.
And you may have to accept xcode's licence agreement.

Then run: 

```r
install.packages("gdtools", type = "source")
```

And re-try installing `esquisse`.

Let me know if it works for you.

Victor

PS: you can find help to install `gdtools` here : https://github.com/davidgohel/gdtools/issues?q=is%3Aissue+is%3Aclosed

**Comment by pvictor** [comment]
Hello,
{esquisse} is now on CRAN and binaries have been build, you can install with : 

```r
install.packages("esquisse")

# with all dependencies
install.packages("esquisse", dependencies = c("Imports", "Suggests"))
```

If you have new installation problems with this command, please open a new issue.

Victor

**Comment by karthikkommalapati** [comment]
Hello,

I have followed the steps as mentioned above, but for some reason, I still keep getting the same error.

Kind Regards,
Karthik 
![Screenshot 2019-10-21 at 21 35 14](https://user-images.githubusercontent.com/43684109/67268066-80dc0a80-f4ab-11e9-85b8-26aab413153a.png)

**Comment by karthikkommalapati** [comment]
The issue now resolved. followed instructions from here and it is working now.

https://community.rstudio.com/t/unable-to-load-packages-libcairo-2-dylib-not-loaded/22754


Kind Regards,
Karthik

**Comment by pvictor** [comment]
Hello Karthik,
Glad you find a solution !

Victor

**Comment by karthikkommalapati** [comment]
Think this issue got to do with the recent Mac software release.

Kind Regards,
Karthik

**Comment by kosukeuetake** [comment]
Many Mac users who recently installed R and Rstudio could not install the esquisse package as well. It worked with my Mac with an old version of R.
