### ISSUE TITLE
Calculated variables

### ISSUE THREAD

**Issue by feinmann** [dreamRs/esquisse#90]
Are there any thoughts on providing calculated fields?

For example in the "Select a dataset" entry: 

1. Select variables to keep: `carat, color`
2. Calculate variable: `mean_carat = group_by(color) %>% mean(carat)`;

**Comment by pvictor** [comment]
In GitHub version, you now have a module (from package [{datamods}](https://dreamrs.github.io/datamods/reference/create-column.html)) to create new columns on the fly : 

<img width="898" alt="image" src="https://github.com/dreamRs/esquisse/assets/4415580/40769055-44d4-47af-bf39-9cd25225bdaa">
