### ISSUE TITLE
data_vars argument is not observed

### ISSUE THREAD

**Issue by DavorJ** [dreamRs/esquisse#91]
[Documentation](https://dreamrs.github.io/esquisse/reference/module-filterDF.html) suggests that _data_vars_ argument is a reactive, but when looking at the source code, only _data_table_ argument is observed. Changing _data_vars_ thus has no effect.

Replacing observeEvent() with observe() would solve the issue.

**Comment by pvictor** [comment]
Thanks for noticing it, `data_vars` is now observed.

Victor
