### ISSUE TITLE
esquisse - 3.6.1

### ISSUE THREAD

**Issue by johnnyfarrell** [dreamRs/esquisse#92]
esquisse won't work on my version of R 

ERROR: lazy loading failed for package ‘esquisse’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/esquisse’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/esquisse’
installation of package ‘/var/folders/ly/zjdtnvqn5j34vwf652wghrsm0000gq/T//RtmpSMcVFQ/file64dc5c6063fd/esquisse_0.2.2.920.tar.gz’ had non-zero exit status
> library(esquisse)
Error: package or namespace load failed for ‘esquisse’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so, 6): Library not loaded: /opt/X11/lib/libfreetype.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so
  Reason: image not found

**Comment by pvictor** [comment]
Hi,
Have you tried to install from CRAN ?

Victor

**Comment by johnnyfarrell** [comment]
Yes I have

________________________________

**Comment by robertwwalker** [comment]
https://github.com/dreamRs/esquisse/issues/67#issuecomment-540144265

You work on a Mac.  Your Mac occasionally needs system level tools for other packages.  In this case, the relevant part of the error is:

dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so, 6): Library not loaded: /opt/X11/lib/libfreetype.6.dylib

Your Mac needs freetype.  Here's how to fix that.

http://macappstore.org/freetype/

You may also need cairo.  It is required for one of the dependencies and is not default installed on Macs.
