### ISSUE TITLE
Can esquisse manage the systemfonts dependencies as part of the package installation?

### ISSUE THREAD

**Issue by sebastiz** [dreamRs/esquisse#94]
Id love to use esquisse more but linix systems seem to need some external dependencies that esquisse doesnt manage as part of the package installation. These are:

1. libfontconfig1-dev which needs to be installed with: sudo apt-get install libfontconfig1-dev
2. Cairo needs to be installed with: sudo apt-get install libcairo2-dev a
3. Also do sudo apt-get install libxt-dev

These need to be run before esquisse is useable. Is it possible to incorporate these in to the package installation process?

**Comment by pvictor** [comment]
Those dependencies are requirements for other packages that {esquisse} depends on and are not directly used by functions in the package.
