### ISSUE TITLE
id field

### ISSUE THREAD

**Issue by rspreafico** [dreamRs/esquisse#95]
Hi,

the chooseDataServer module will by default drop the ID column of an imported dataset. The user needs to point and click to retain it. Would it be possible to add an option to programmatically direct whether the ID column should be retained or not by default?

Thank you

**Comment by pvictor** [comment]
Hello,

`chooseDataServer` has a new argument `selectedTypes` to allow to select ID column by default.
Install from GitHub to try it out!

Victor

**Comment by rspreafico** [comment]
Works beautifully! Thank you!!!
