### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by johnnyfarrell** [dreamRs/esquisse#96]
Hello,
{esquisse} is now on CRAN and binaries have been build, you can install with : 

```r
install.packages("esquisse")

# with all dependencies
install.packages("esquisse", dependencies = c("Imports", "Suggests"))
```

If you have new installation problems with this command, please open a new issue.

Victor

_Originally posted by @pvictor in https://github.com/dreamRs/esquisse/issues/9#issuecomment-426545469_

**Comment by johnnyfarrell** [comment]
Hi I still have the same issue as esquire will not load for me on my machine

**Comment by pvictor** [comment]
Hello,
Can you try to install from GitHub in a fresh R session (no other sessions openned) ?

```r
remotes::install_github("dreamRs/esquisse")
```

and tell me the results

Victor

**Comment by johnnyfarrell** [comment]
Hi Victor,

I have attached a file to show the error I am receiving.

Thanks
<img width="1077" alt="Screenshot 2020-01-16 at 14 54 31" src="https://user-images.githubusercontent.com/48764725/72535319-426aa780-3870-11ea-86a1-3300e029b7fc.png">

**Comment by pvictor** [comment]
Thanks for trying, your're on MacOS right ? Have you installed X11 ?

**Comment by johnnyfarrell** [comment]
Yes I am on MacOs Mojave. No I don't have X11 installed?

**Comment by pvictor** [comment]
Thx, can you install X11 and retry (in a fresh R session like before) ?
This is linked to this : https://github.com/r-lib/systemfonts/issues/17

**Comment by johnnyfarrell** [comment]
> Thx, can you install X11 and retry (in a fresh R session like before) ?
> This is linked to this : [r-lib/systemfonts#17](https://github.com/r-lib/systemfonts/issues/17)

That's worked perfectly. I got it working after installing the X11. Thank you

**Comment by pvictor** [comment]
Great!
